### ISSUE TITLE
mark_duplicates command - error relating to a lack of bam indexes being generated for intermediary bam

### ISSUE THREAD

**Issue by kevjp** [chapmanb/bcbio-nextgen#1091]
Hi 
I am trying to run some amplicon data through your pipeline but setting the mark_duplicates to false seems to throw an error relating to the absence of a bam index file being generated for one of the bam intermediary files ending `reorder-firgs-gatkfilter.bam`. Not sure if I am setting this correctly but if I remove the setting it seems to run fine.
My yaml file looks like:
```
upload:
  dir: final
details:
- algorithm:
    merge_bamprep: true
    mark_duplicates: false
    realign: false
    recalibrate: false
    variantcaller: [gatk-haplotype, samtools, platypus]
    validate: ../input/regions.vcf
    ensemble:
      numpass: 2
  analysis: variant2
  description: NGSfiletest
  files: [/home/file1_L001_001_1.fastq.gz, /home/file2_L001_001_2.fastq.gz]
  genome_build: GRCh37
fc_date: '2015-10-09'
fc_name: qxtindel1
```
