### ISSUE TITLE
batch doesn't support an array?

### ISSUE THREAD

**Issue by whitejbiii** [chapmanb/bcbio-nextgen#1102]
According to the configuration documentation, "batch:" can take either a single batch-name string, "name1", or a list of batch names, "[name1, name2]". When I specify a list of batch names, however, bcbio seems to interpret the list as a single string, causing failures like this:
```
[0:apply]: CalledProcessError: Command 'set -o pipefail; gunzip -c /data/fastq/alldata/Exome_Validation_Run1/bcbio/work/NA-trio-123/gemini/['NA12878-2-only', 'NA-trio-2']-freebayes.vcf.gz | sed 's/ID=AD,Number=./ID=AD,Number=R/' | vt decompose -s - | awk '{ gsub("./-65", "./."); print $0 }'| bgzip -c > /data/fastq/alldata/Exome_Validation_Run1/bcbio/work/NA-trio-123/gemini/tx/tmp1NdTmu/['NA12878-2-only', 'NA-trio-2']-freebayes-decompose.vcf.gz
decompose v0.5

options:     input VCF file        -
         [s] smart decomposition   true (experimental)
         [o] output VCF file       -

gzip: /data/fastq/alldata/Exome_Validation_Run1/bcbio/work/NA-trio-123/gemini/[NA12878-2-only,.gz: No such file or directory
gzip: NA-trio-2]-freebayes.vcf.gz: No such file or directory
[bcf_ordered_reader.cpp:49 BCFOrderedReader] Not a VCF/BCF file: -
[bgzip] No such file or directory: NA-trio-2]-freebayes-decompose.vcf.gz
' returned non-zero exit status 1
```
My configuration file is a bit tricky, with different samples in partially overlapping groups of batches, like so:
```
  - files: [...]
    description: NA12878-1
    metadata:
      batch: [NA12878-1-only, NA-trio-1]
...
   - files: [...]
    description: NA12892
    metadata:
      batch: [NA-trio-1, NA-trio-2, NA-trio-3]
```
Am I doing something wrong, or is a list of batch values not quite supported for this case?
