### ISSUE TITLE
Attempting to run two different pipelines using the same configuration file

### ISSUE THREAD

**Issue by kevjp** [chapmanb/bcbio-nextgen#1139]
Hi
I am trying to run two different pipelines simultaneously. I need to first run the bam files through `bam_clean: picard`  before going through two different pipelines. I have set up my config csv files as:

```
samplename,description,realign,recalibrate,validate,variantcaller
Sample1,Sample1HC;Sample1FB,gatk;false,gatk;false,/home/Documents/Expected.vcf,gatk-haplotype;freebayes
```

The yaml is set up as:

```
upload:
  dir: final
details:
- algorithm:
    aligner: false
    bam_clean: picard
    merge_bamprep: false
    mark_duplicates: false
    realign: gatk
    recalibrate: gatk
    variantcaller: 
      - gatk-haplotype
    validate: ../input/formatted_regions.vcf
  analysis: variant2
  description: filedescription
  files: /home/Documents/generic.bam
  genome_build: GRCh37
fc_date: '2015-11-09'
fc_name: qxtindel2

```
When I run the analysis the bam_clean seems to occur fine but it creates a folder Sample1HC;Sample1FB i.e. it does not seem to recognise the description field as a semi-colon separated list. Later in the next stage it is then looking for the folder Sample1HC which is the first part of the semi-colon separated list so it then does seem to recognise the description field as a list. I would like the pipeline to perform the bam_clean just once but then I want the generated files to be put through two different analysis streams, one that includes realign,recalibrate,validate and variantcaller set to gatk, gatk, /home/Documents/Expected.vcf and gatk-haplotype and another analysis stream set to false, false, /home/Documents/Expected.vcf and freebayes. Is this possible, perhaps my interpretation of the docs is incorrect.
