### ISSUE TITLE
Sample variant call VCF files not copied to upload directory

### ISSUE THREAD

**Issue by funnell** [chapmanb/bcbio-nextgen#1174]
Here is a portion of my config file:
```
- algorithm:
    align_split_size: 5000000
    aligner: novoalign
    mark_duplicates: true
    platform: illumina
    realign: gatk
    recalibrate: gatk
    remove_lcr: true
    variantcaller: freebayes
  analysis: variant2
  description: SA733_A51755
  files:
  - /shahlab/tfunnell/bcbio_work/CX5461_yeast/input/SA733_A51755_C7GJEANXX_8_1.fastq.gz
  - /shahlab/tfunnell/bcbio_work/CX5461_yeast/input/SA733_A51755_C7GJEANXX_8_2.fastq.gz
  genome_build: sacCer3
  metadata:
    batch: SA733
    phenotype: normal
...
upload:
  dir: /shahlab/tfunnell/bcbio_work/CX5461_yeast/output
```

There is output in the freebayes directory, but no VCF files in the upload directory; only the bam files, qc output and project related files have been copied.
