### ISSUE TITLE
platypus variant calling - region list

### ISSUE THREAD

**Issue by rjsicko** [chapmanb/bcbio-nextgen#1223]
I'm getting an error when trying to run platypus joint calling in bcbio.

```
[2016-02-11T13:22Z] platypus variant calling
[2016-02-11T13:22Z] 2016-02-11 08:22:01,002 - ERROR - Platypus found no regions to search. Check that you are using the correct reference FASTA file or have specified the 'regions' argument correctly
```

command used:
```
[2016-02-11T13:19Z] platypus callVariants --regions=/media/sf_BigShare/16014_wes_pilot/work/platypus/3/HapMap-3_173996632_189507659-raw-platypusregion.list --bamFiles=/media/sf_BigShare/16014_wes_pilot/work/bamprep/HapMap/3/13_2016-02-01_project-merged-sort-3_173996632_189507659-prep.bam --refFile=/usr/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --output=- --logFileName /dev/null --verbosity=1 --assemble=1 --hapScoreThreshold 10 --scThreshold 0.99 --filteredReadsFrac 0.9 --rmsmqThreshold 20 --qdThreshold 0 --abThreshold 0.0001 --minVarFreq 0.0 | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}' | vcfallelicprimitives --keep-geno | vcffixup - | vcfstreamsort | bgzip -c > /home/rsicko/tmp/bcbiotx/7e85cbd5-c246-4ba1-b924-1803b0da2eee/tmpE0kpki/HapMap-3_173996632_189507659-raw.vcf.gz
```

List file and reference file are both present and accessible. This same error appears to be occurring for all regions. I'm not sure if it is something I specified incorrectly, a bcbio error or a platypus error.
Additional info - I'm running ensemble variant calling and it appears gatk, freebayes and samtools are calling variants. 

portion of project.yaml file.
```
details:
- algorithm:
    aligner: bwa
    effects: vep
    ensemble:
      classifier-params:
        type: svm
      classifiers:
        balance:
        - AD
        - FS
        - Entropy
        calling:
        - ReadPosEndDist
        - PL
        - PLratio
        - Entropy
        - NBQ
      format-filters:
      - DP < 4
      trusted-pct: 0.5
    jointcaller:
    - gatk-haplotype-joint
    - freebayes-joint
    - platypus-joint
    - samtools-joint
    mark_duplicates: true
    mixup_check: qsignature
    phasing: gatk
    realign: false
    recalibrate: gatk
    remove_lcr: true
    variant_regions: /media/sf_BigShare/Project_Tsai_Project_025/agilent_files/S04380219_Covered_noChr.bed
    variantcaller:
    - gatk-haplotype
    - freebayes
    - platypus
    - samtools
  analysis: variant2
  description: A06551
  files:
  - /media/sf_BigShare/16014_wes_pilot/work/fastq/merged/A06551_R1.fastq.gz
  - /media/sf_BigShare/16014_wes_pilot/work/fastq/merged/A06551_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: batch1
    phenotype: affected
    sex: male
```
