### ISSUE TITLE
No callable regions found

### ISSUE THREAD

**Issue by m4merg** [chapmanb/bcbio-nextgen#1224]
With 0.9.6a version upon running (Illumina Trusight One Panel on MiSeq 300b.p. reads) I get the following error:

>ValueError: No callable regions found from BAM file. Alignment regions might not overlap with regions found in your 'variant_regions' BED: /home/bioinform/samples/25/align/25/25-sort.bam

If I look at align/25/25-sort-callable.bed I see that none of the chromosomes have callable regions:
>1       0       249250621       NO_COVERAGE
2       0       243199373       NO_COVERAGE
3       0       198022430       NO_COVERAGE
e.t.c

Though BAM file at  align/25/25-sort.bam is ok:
>11276878 + 0 in total (QC-passed reads + QC-failed reads)
58538 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
11253007 + 0 mapped (99.79% : N/A)
11218340 + 0 paired in sequencing
5609170 + 0 read1
5609170 + 0 read2
11109302 + 0 properly paired (99.03% : N/A)
11171990 + 0 with itself and mate mapped
22479 + 0 singletons (0.20% : N/A)
34700 + 0 with mate mapped to a different chr
19857 + 0 with mate mapped to a different chr (mapQ>=5)

And based on previous analysis of this data I know that there is enough coverage to detect variants. For example (based on samtools depth of align/25/25-sort.bam):
>1	16974418	1505
1	16974419	1465
1	16974420	1466
1	16974421	1466
1	16974422	1463
1	16974423	1463
1	16974424	1445
1	16974425	1442
1	16974426	1442
1	16974427	1442
1	16974428	1442
1	16974429	1434

**So why do I get no callable regions?**

The configuration file i use is:
```
details:
 - algorithm:
    aligner: bwa
    align_split_size: 5000000
    nomap_split_targets: 100
    mark_duplicates: false
    recalibrate: true
    realign: true
    remove_lcr: true
    platform: illumina
    quality_format: standard
    variantcaller: [mutect, freebayes, vardict, varscan]
    indelcaller: [scalpel, pindel, sid]
    ensemble:
      numpass: 2
    min_allele_fraction: 5
    variant_regions: /home/bioinform/reference/TSO/TruSight_One_v1.1.bed
    validate: /home/bioinform/reference/validateByCosmicCNTMore1.vcf.gz
    validate_regions: /home/bioinform/reference/TSO/TruSight_One_v1.1.bed
    svcaller: [cnvkit, lumpy, delly]
    coverage_interval: /home/bioinform/reference/TSO/TruSight_One_v1.1.bed
    svprioritize: /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/prioritization/MIG.bed
    svvalidate:
       DEL: /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/validation/dream-syn3/truth_DEL.bed
       DUP: /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/validation/dream-syn3/truth_DUP.bed
       INS: /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/validation/dream-syn3/truth_INS.bed
       INV: /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/validation/dream-syn3/truth_INV.bed
  analysis: variant2
  description: 25
  #files: ../input/synthetic.challenge.set3.tumor.bam
  files:
    - /home/bioinform/samples/25/25_S3_L001_R1_001.fastq
    - /home/bioinform/samples/25/25_S3_L001_R2_001.fastq
  genome_build: GRCh37
  metadata:
    batch: syn3
    phenotype: tumor
fc_date: '2016-02-01'
fc_name: ''
upload:
  dir: ../final
```
