### ISSUE TITLE
bcbio and heterogeneity 

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1229]
Sorry, I am curious to know which parameter must be set in the project.yam in order to run phylowgs and bubble tree?

thanks!

**Comment by chapmanb** [comment]
Alessandro;
There is a `hetcaller` target which specifies these. However, it's currently undocumented as they're not completely stable and validated. PhyloWGS still needs work on the Battenberg caller as input. BubbleTree should work with CNVkit as an input:
```
svcaller: cnvkit
hetcaller: bubbletree
```
but we're not yet sure how well tuned the outputs are because of lack of good validation sets. Sorry about all the cavaets but hope this helps with the current status.

**Comment by apastore** [comment]
Thanks a lot it was curiosity

**Comment by choosehappy** [comment]
I was wondering if any updates have been made in this? 

I see that the code is still in place, but when enabling the hetcaller: bubbletree option, in the end, no output was produced (also no "bubble" tree at all in the command log)

**Comment by chapmanb** [comment]
Thanks much for trying this out. bubbletree should still be supported if you have CNVkit calling in your processing as well. Would you be able to share your configuration where it gets skipped? What kind of inputs do you have: tumor-only or tumor/normal paired?

Practically, we're working on improving heterogeneity calling and recently added TitanCNA support which we'll match up existing PhyloWGS support soon. These are for tumor/normal paired samples only, though, and next steps are to integerate PureCN to handle the tumor-only cases.

Thanks again for testing these.

**Comment by choosehappy** [comment]
These are tumor/normal paired samples


below you can find the yaml file, as you see, i've launched ALL the missles :)  

(interally we're doing some testing)

```
details:
- algorithm:
    aligner: bwa
    effects: vep
    ensemble:
      numpass: 2
    hetcaller: bubbletree
    hlacaller: optitype
    indelcaller: false
    kraken: minikraken
    mark_duplicates: true
    realign: true
    recalibrate: true
    svcaller:
    - cnvkit
    - lumpy
    - manta
    svprioritize: cancer/civic
    tools_off: gemini
    tools_on:
    - lumpy_usecnv
    - bnd-genotype
    - svplots
    - qualimap
    variantcaller:
    - vardict
    - mutect
    - freebayes
    - varscan
  analysis: variant2
  description: N1
  files:
  - /data/CNV.valid/N1.R1.fastq.gz
  - /data/CNV.valid/N1.R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: b1
    phenotype: normal
- algorithm:
    aligner: bwa
    effects: vep
    ensemble:
      numpass: 2
    hetcaller: bubbletree
    hlacaller: optitype
    indelcaller: false
    kraken: minikraken
    mark_duplicates: true
    realign: true
    recalibrate: true
    svcaller:
    - cnvkit
    - lumpy
    - manta
    svprioritize: cancer/civic
    tools_off: gemini
    tools_on:
    - lumpy_usecnv
    - bnd-genotype
    - svplots
    - qualimap
    variantcaller:
    - vardict
    - mutect
    - freebayes
    - varscan
  analysis: variant2
  description: T1
  files:
  - /data/CNV.valid/T1.R1.fastq.gz
  - /data/CNV.valid/T1.R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: b1
    phenotype: tumor
fc_name: P1
upload:
  dir: ../final

```


not sure where its supposed to be run, but the command log has no mention of bubbletree:

```
root@sib-pc25:/export/big/ajanowcz/CNV.valid/P1/final/2017-11-29_P1# cat bcbio-nextgen-commands.log | grep bub
root@sib-pc25:/export/big/ajanowcz/CNV.valid/P1/final/2017-11-29_P1#

```

as well one of the outputs is a pdf but no relevant ones seems produced:

```
root@sib-pc25:/export/big/ajanowcz/CNV.valid/P1# find . | grep pdf
./work/align/N1/hla/OptiType-HLA-A_B_C/2017_11_28_01_39_39/2017_11_28_01_39_39_coverage_plot.pdf
./work/align/T1/hla/OptiType-HLA-A_B_C/2017_11_28_01_49_27/2017_11_28_01_49_27_coverage_plot.pdf
./work/structural/T1/bins/T1-normalized-diagram.pdf
./work/structural/T1/bins/T1-normalized-scatter.pdf
./work/structural/T1/bins/T1-normalized-scatter_global.pdf
```

Is there something else i can show you to help?
