### ISSUE TITLE
mutect config file missing error. 

### ISSUE THREAD

**Issue by mortunco** [chapmanb/bcbio-nextgen#1280]
Hi,

I am getting an error about mutect config file is not found. However, I dont have a screen shot neither there is not an evidence related with this problem in the log files. I followed all the steps written on the cancer-tumor example. 

What might be the reason that cause this type of error. also when I looked for the callers output. There is not a single mutect variant call whereas all the callers have output for 22+XY chromosomes. Which specific log should I share with you to solve this error ? Could you lead me to find this problem ?

Also when I looked at the performance, (I am running on Amazon Web Service single instance r3.xlarge instance), I have seen that CPU seems more important than the ram that is used. Could you suggest me a memory size that will capable of running 50-70x coverage bam files tumor-cancer mutation calling and this tutorial as well. I am thinking of saving money from memory and allocate it for buying cpu power. 

Below I am sharing my config file that I used to run this tutorial. Also, I share the structure of the outputs.

Thank you for your help,

Best,

Tunc.

```
[ec2-user@ip-172-31-57-166 config]$ cat cancer-dream-syn3.yaml 
# Cancer tumor/normal calling evaluation using synthetic dataset 3
# from the ICGC-TCGA DREAM challenge:
# https://www.synapse.org/#!Synapse:syn312572/wiki/62018
---
details:
- algorithm:
    aligner: bwa
    align_split_size: 5000000
    nomap_split_targets: 100
    mark_duplicates: true
    recalibrate: true
    realign: true
    remove_lcr: true
    platform: illumina
    quality_format: standard
    variantcaller: [mutect, freebayes, vardict, varscan]
    indelcaller: false
    ensemble:
      numpass: 2
    variant_regions: /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/input/NGv3.bed
    # svcaller: [cnvkit, lumpy, delly]
    # coverage_interval: amplicon
  analysis: variant2
  description: syn3-normal
  #files: ../input/synthetic.challenge.set3.normal.bam
  files:
    - /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/input/synthetic_challenge_set3_normal_NGv3_1.fq.gz
    - /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/input/synthetic_challenge_set3_normal_NGv3_2.fq.gz
  genome_build: GRCh37
  metadata:
    batch: syn3
    phenotype: normal
- algorithm:
    aligner: bwa
    align_split_size: 5000000
    nomap_split_targets: 100
    mark_duplicates: true
    recalibrate: true
    realign: true
    remove_lcr: true
    platform: illumina
    quality_format: standard
    variantcaller: [mutect, freebayes, vardict, varscan]
    indelcaller: false
    ensemble:
      numpass: 2
    variant_regions: /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/input/NGv3.bed
    validate: /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/input/synthetic_challenge_set3_tumor_20pctmasked_truth.vcf.gz
    validate_regions: /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/input/synthetic_challenge_set3_tumor_20pctmasked_truth_regions.bed
    # svcaller: [cnvkit, lumpy, delly]
    # coverage_interval: amplicon
  #   svvalidate:
  #     DEL: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_DEL.bed
  #     DUP: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_DUP.bed
  #     INS: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_INS.bed
  #     INV: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_INV.bed
  analysis: variant2
  description: syn3-tumor
  #files: ../input/synthetic.challenge.set3.tumor.bam
  files:
    - /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/input/synthetic_challenge_set3_tumor_NGv3_1.fq.gz
    - /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/input/synthetic_challenge_set3_tumor_NGv3_2.fq.gz
  genome_build: GRCh37
  metadata:
    batch: syn3
    phenotype: tumor
fc_date: '2014-08-13'
fc_name: dream-syn3
upload:
  dir: /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/final
```

```
.
└── cancer-dream-syn3
    ├── config
    ├── input
    └── work
        ├── align
        │   ├── syn3-normal
        │   │   ├── 1_2014-08-13_dream-syn3-sort-callable-split
        │   │   │   └── tx
        │   │   ├── split
        │   │   │   └── tx
        │   │   └── tx
        │   └── syn3-tumor
        │       ├── 2_2014-08-13_dream-syn3-sort-callable-split
        │       │   └── tx
        │       ├── split
        │       │   └── tx
        │       └── tx
        ├── align_prep
        │   └── tx
        ├── bamprep
        │   ├── syn3-normal
        │   │   ├── 1
        │   │   │   └── tx
        │   │   ├── 10
        │   │   │   └── tx
        │   │   ├── 11
        │   │   │   └── tx
        │   │   ├── 12
        │   │   │   └── tx
        │   │   ├── 13
        │   │   │   └── tx
        │   │   ├── 14
        │   │   │   └── tx
        │   │   ├── 15
        │   │   │   └── tx
        │   │   ├── 16
        │   │   │   └── tx
        │   │   ├── 17
        │   │   │   └── tx
        │   │   ├── 18
        │   │   │   └── tx
        │   │   ├── 19
        │   │   │   └── tx
        │   │   ├── 2
        │   │   │   └── tx
        │   │   ├── 20
        │   │   │   └── tx
        │   │   ├── 21
        │   │   │   └── tx
        │   │   ├── 22
        │   │   │   └── tx
        │   │   ├── 3
        │   │   │   └── tx
        │   │   ├── 4
        │   │   │   └── tx
        │   │   ├── 5
        │   │   │   └── tx
        │   │   ├── 6
        │   │   │   └── tx
        │   │   ├── 7
        │   │   │   └── tx
        │   │   ├── 8
        │   │   │   └── tx
        │   │   ├── 9
        │   │   │   └── tx
        │   │   ├── noanalysis
        │   │   │   └── tx
        │   │   ├── nochrom
        │   │   │   └── tx
        │   │   ├── X
        │   │   │   └── tx
        │   │   └── Y
        │   │       └── tx
        │   └── syn3-tumor
        │       ├── 1
        │       │   └── tx
        │       ├── 10
        │       │   └── tx
        │       ├── 11
        │       │   └── tx
        │       ├── 12
        │       │   └── tx
        │       ├── 13
        │       │   └── tx
        │       ├── 14
        │       │   └── tx
        │       ├── 15
        │       │   └── tx
        │       ├── 16
        │       │   └── tx
        │       ├── 17
        │       │   └── tx
        │       ├── 18
        │       │   └── tx
        │       ├── 19
        │       │   └── tx
        │       ├── 2
        │       │   └── tx
        │       ├── 20
        │       │   └── tx
        │       ├── 21
        │       │   └── tx
        │       ├── 22
        │       │   └── tx
        │       ├── 3
        │       │   └── tx
        │       ├── 4
        │       │   └── tx
        │       ├── 5
        │       │   └── tx
        │       ├── 6
        │       │   └── tx
        │       ├── 7
        │       │   └── tx
        │       ├── 8
        │       │   └── tx
        │       ├── 9
        │       │   └── tx
        │       ├── noanalysis
        │       │   └── tx
        │       ├── nochrom
        │       │   └── tx
        │       ├── X
        │       │   └── tx
        │       └── Y
        │           └── tx
        ├── bedprep
        │   └── tx
        ├── checkpoints_parallel
        ├── freebayes
        │   ├── 1
        │   │   └── tx
        │   ├── 10
        │   │   └── tx
        │   ├── 11
        │   │   └── tx
        │   ├── 12
        │   │   └── tx
        │   ├── 13
        │   │   └── tx
        │   ├── 14
        │   │   └── tx
        │   ├── 15
        │   │   └── tx
        │   ├── 16
        │   │   └── tx
        │   ├── 17
        │   │   └── tx
        │   ├── 18
        │   │   └── tx
        │   ├── 19
        │   │   └── tx
        │   ├── 2
        │   │   └── tx
        │   ├── 20
        │   │   └── tx
        │   ├── 21
        │   │   └── tx
        │   ├── 22
        │   │   └── tx
        │   ├── 3
        │   │   └── tx
        │   ├── 4
        │   │   └── tx
        │   ├── 5
        │   │   └── tx
        │   ├── 6
        │   │   └── tx
        │   ├── 7
        │   │   └── tx
        │   ├── 8
        │   │   └── tx
        │   ├── 9
        │   │   └── tx
        │   ├── X
        │   │   └── tx
        │   └── Y
        │       └── tx
        ├── inputs
        │   └── data
        │       └── annotations
        ├── log
        ├── mutect
        │   └── 1
        ├── provenance
        ├── regions
        │   └── tx
        ├── tx
        └── vardict
            ├── 1
            │   └── tx
            ├── 10
            │   └── tx
            ├── 11
            │   └── tx
            ├── 12
            │   └── tx
            ├── 13
            │   └── tx
            ├── 14
            │   └── tx
            ├── 15
            │   └── tx
            ├── 16
            │   └── tx
            ├── 17
            │   └── tx
            ├── 18
            │   └── tx
            ├── 19
            │   └── tx
            ├── 2
            │   └── tx
            ├── 20
            │   └── tx
            ├── 21
            │   └── tx
            ├── 22
            │   └── tx
            ├── 3
            │   └── tx
            ├── 4
            │   └── tx
            ├── 5
            │   └── tx
            ├── 6
            │   └── tx
            ├── 7
            │   └── tx
            ├── 8
            │   └── tx
            ├── 9
            │   └── tx
            ├── X
            │   └── tx
            └── Y
                └── tx

237 directories
```
