### ISSUE TITLE
GATK jvm options are ignored even in single core setups

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1295]
And this causes errors in the long run.

Excerpt from ``bcbio_system.yaml``:

```yaml
  default:
    cores: 8
    jvm_opts:
    - -Xms750m
    - -Xmx1500m
    memory: 2G
  dexseq:
    memory: 10g
  express:
    memory: 8g
  gatk:
    dir: /opt/bcbio/toolplus/gatk/3.5-0-g36282e4
    jvm_opts:
    - -Xms500m
    - -Xmx1500m
  gatk-haplotype:
    jvm_opts:
    - -Xms500m
    - -Xmx1500m
```

But afterwards (even in single core runs), I get (notice the options):

```
subprocess.CalledProcessError: Command 'set -o pipefail; java -Xms166m -Xmx500m -XX:+UseSerialGC  # etc etc
```
How are those parameters set? The machine has 32G RAM (and 8 cores) and it's running things locally (even with ``-t local -n 1`` I see this issue). This occurs with 0.9.6.
