### ISSUE TITLE
Identical data and config produce inconsistent variant calls.

### ISSUE THREAD

**Issue by sxv** [chapmanb/bcbio-nextgen#1297]
Hi, I ran a tumor-only case from fastq to VCF through bcbio_nextgen in June 2015 and again in January 2016. While the intermediate BAM files and even the individual VCF filesizes are nearly identical ([exhibit A](https://s3.amazonaws.com/f.cl.ly/items/1N1l0w210W0H3d2J0k1b/Image%202016-03-31%20at%206.34.31%20PM.png?v=6bb38078)), the ensemble VCFs differ tremendously. The more recent run resulted in an ensemble (numpass: 2) of 1.4mb while the prior run resulted in only 28k.

To dig into this, I looked for a specific position in the individual callers' VCFs that made it into the more recent ensemble report but not the first one. The result ([exhibit B](https://s3.amazonaws.com/f.cl.ly/items/2o0R0D2U2n242j3l2Z2V/Image%202016-03-31%20at%206.52.35%20PM.png?v=4b8f5fa2)) reveals that in the more recent run, these positions were classified as LowPriority by both FreeBayes and VarDict, while they were PASS in the first run.

Is this known behavior? What is the reason for this? This difference has a drastic impact on the resulting analysis so I would like to fully understand what is happening here. Thanks!

Example config:

```yaml
# Template for tumor-only variant calling
---
fc_date: 20150602
fc_name: dcis_2_6
upload:
  dir: /final/
resources:
  tmp:
    dir: ../tmp
details:
  - analysis: variant2
    genome_build: hg19
    metadata:
      batch: dcis2
      phenotype: tumor
    description: dcis2t
    files: [./R1_001.fastq.gz, ./R2_001.fastq.gz]
    algorithm:
      aligner: bwa
      mark_duplicates: true
      recalibrate: true
      realign: true
      platform: illumina
#      tools_off: [gemini]
      variantcaller: [mutect, freebayes, vardict-java]
      ensemble:
        numpass: 2
```
