### ISSUE TITLE
small RNA-seq analysis hangs

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1395]
Hi guys!

I'm trying to run small RNA-seq on Solanum tuberosum.
It did cutadapt,  STAR, sambamba and then it hangs on 

[mydir]/tools/bcbio/anaconda/bin/seqcluster cluster -o [mydir]/mirna/work/seqcluster/cluster -m [mydir]/mirna/work/seqcluster/prepare/seqs.ma -a [mydir]/mirna/work/align/seqs.bam -r [mydir]/tools/bcbio/genomes/stuberosum/soltub3/seq/soltub3.fa -g [mydir]/tools/bcbio/genomes/stuberosum/soltub3/srnaseq/srna-transcripts.gtf

Hopefully it is not an HPF or Filesystem issue, because I did it two times and for the last run it was hanging for 3 days.

I would appreciate any useful ideas how to run this analysis.
Sergey

**Comment by lpantano** [comment]
Hi,

sorry about the problem. Can you send me the log files? It could happen that the small RNA is not standard so this tool won’t work well. I can try to make run this only if the data looks good for that. 

cheers

**Comment by naumenko-sa** [comment]
I've sent logs by email. Thanks. Sergey

**Comment by lpantano** [comment]
Hi,

I add a workaround to avoid seqcluster if you add under `algorithm`:

```
details:
  - analysis: smallRNA-seq
    algorithm:
      tools_off: ["seqcluster"]
```

You will need to update to last development: `bcbio_nextgen.py upgrade -u development --tools`

I didn't see in the LOG files the step to map to miRNAs so I want to check you have all the files. What do you have under you GENOME folder? Do you see a SRNASEQ folder with files there? If not i can help you to set up this.

Let me know about the annotation files to see how I can help you further.

cheers

**Comment by naumenko-sa** [comment]
Yes, I have hairpin.fa  miRNA.str  srna-transcripts.gtf in my genome folder. I did custom genome installation as described in the docs.
bcbio_setup_genome.py -c 5 -f /hpf/largeprojects/ccmbio/naumenko/mirna/GCF_000004515.4_Glycine_max_v2.0_genomic.fna --gff3 -g \
 /hpf/largeprojects/ccmbio/naumenko/mirna/GCF_000004515.4_Glycine_max_v2.0_genomic.gff -n glycinemax -b glymax2 --mirbase gma -i star \
 --srna_gtf /hpf/largeprojects/ccmbio/naumenko/mirna/GCF_000004515.4_Glycine_max_v2.0_genomic.gtf

I've found that standard gff annotation files had a couple of errors (some exons seemed to be on the wrong strand)
"all group members must be on same seq and strand invalid gffGroup detected on line"

Thanks, I'll try your workaround.

**Comment by lpantano** [comment]
Ok, i changed recently a couple of things there, so maybe I need to update the genome_setup script. It could be that for you this is enough, but you will need to change the `seq/genome-resources.yaml` file to this:

srnaseq:
    srna-transcripts: ../srnaseq/srna-transcripts.gtf
    mirbase-hairpin: ../srnaseq/hairpin.fa




sorry about that, I will update the script to do this the right way.

**Comment by naumenko-sa** [comment]
Sorry, it seems that it stucks on the same step.
I've updated to development version, I'm using tools_off: ["seqcluster"] in the config, and soltub3/seq contains soltub3-resources.yaml has lines
srnaseq:
  mirbase: ../srnaseq/hairpin.fa
  srna-transcripts: ../srnaseq/srna-transcripts.gtf

**Comment by lpantano** [comment]
Did you updated bcbio? did you find any error when updating? `bcbio_nextgen.py upgrade -u development --tools`

remember to change `mirbase` to `mirbase-hairpin` in the resources.yaml file.

**Comment by naumenko-sa** [comment]
Thanks, `mirbase-hairpin` help. I've passed this step! 
Now it complains 

[2016-05-16T19:48Z] Timing: small RNA annotation
[2016-05-16T19:48Z] multiprocessing: srna_annotation
[2016-05-16T19:48Z] Do miRNA annotation for /hpf/largeprojects/ccmbio/naumenko/mirna/work/trimmed/HI_3550_004_RPI1_R4215_R1/HI.3550.004.RPI1.R4215_R1.clean.trimming.fastq
[2016-05-16T19:48Z] Format is not tabular,guessing fasta
[2016-05-16T19:48Z] species not found: stuberosum
[2016-05-16T19:48Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/galaxy/../anaconda/bin/miraligner -Xms750m -Xmx4500m -freq -sub 1 -trim 3 -add 3 -s stuberosum -i /hpf/largeprojects/ccmbio/naumenko/mirna/work/trimmed/HI_3550_004_RPI1_R4215_R1/HI.3550.004.RPI1.R4215_R1.clean.trimming.fastq -db /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/stuberosum/soltub3/srnaseq  -o /hpf/largeprojects/ccmbio/naumenko/mirna/work/mirbase/HI_3550_004_RPI1_R4215_R1/tx/tmpk2wqwU/HI_3550_004_RPI1_R4215_R1
Format is not tabular,guessing fasta
species not found: stuberosum
' returned non-zero exit status 1

Can't find hairpin.fa?

SN

**Comment by lpantano** [comment]
Hi,

in this case you need to specify `species: stu` that is the ID that mirbase uses for this species I think. Is that what you have in your config YAML file?

**Comment by naumenko-sa** [comment]
Thanks, I've moved forward with stu! However it now hangs on seqcluster. It is something strange: I've switched seqcluster off.

[2016-05-17T18:54Z] Skipping seqcluster
[2016-05-17T18:54Z] Running seqcluster.
[2016-05-17T18:55Z] INFO Run cluster
[2016-05-17T18:55Z] INFO Checking parameters and files
[2016-05-17T18:55Z] INFO Output dir will be: /hpf/largeprojects/ccmbio/naumenko/mirna/work/seqcluster/cluster
[2016-05-17T18:55Z] INFO Clean bam file with highly repetitive reads with low counts. sum(counts)/n_hits > 1%
[2016-05-17T18:56Z] INFO Using /hpf/largeprojects/ccmbio/naumenko/mirna/work/align/seqs_rmlw.bam file
[2016-05-17T18:56Z] INFO Parsing matrix file
[2016-05-17T18:57Z] INFO counts after: 41210144
[2016-05-17T18:57Z] INFO # sequences after: 843754
[2016-05-17T18:57Z] INFO Cleaning bam file
[2016-05-17T18:57Z] INFO counts after: 36994135
[2016-05-17T18:57Z] INFO # sequences after: 642842
[2016-05-17T18:57Z] INFO Parsing aligned file
[2016-05-17T18:57Z] INFO Merging position

**Comment by lpantano** [comment]
can you send me the config yaml file you are using? 
i get seqcluster skipped with the last version of bcbio. Did u updated successfully?  any error or messages?

sent not from my computer

**Comment by naumenko-sa** [comment]
Hi Lorena!

I've updated successfully, now my version is
bcbio_nextgen.py -v
0.9.8a0

Config file:
``` 
details:
- algorithm:
    aligner: star
    adapters: ["TGGAATTCTCGGGTGC"]
    species: stu
    tools_off: ["seqcluster"]
  analysis: smallRNA-seq
  description: HI.3550.004.RPI1.R4215_R1
  files:
  - /home/naumenko/work/mirna/input/HI.3550.004.RPI1.R4215_R1.fastq.gz
  genome_build: soltub3
- algorithm:
    aligner: star
    adapters: ["TGGAATTCTCGGGTGC"]
    species: stu
    tools_off: ["seqcluster"]
  analysis: smallRNA-seq
  description: HI.3550.004.RPI3.R4217_R1
  files:
  - /home/naumenko/work/mirna/input/HI.3550.004.RPI3.R4217_R1.fastq.gz
  genome_build: soltub3
fc_date: '2016-05-10'
fc_name: srna1
upload:
  dir: ../final
```
Thanks!
Sergey
