### ISSUE TITLE
Template command for qsignature

### ISSUE THREAD

**Issue by sluke123** [chapmanb/bcbio-nextgen#1423]
Template command on the yaml file with qsignature duplicates the entry in the alignment section and the top level of the sample yaml

**Comment by lpantano** [comment]
Hi,

sorry about that. I am not sure I understand, can you give an example? That way I can try to find the bug and a solution.

cheers

**Comment by mjafin** [comment]
Instead of this:
```
- algorithm:
    aligner: false
    mark_duplicates: false
    mixup_check: qsignature
    realign: false
    recalibrate: false
    variantcaller: false
  analysis: variant2
  description: 020-20
  files:
  - /path/to/ready.bam
  genome_build: hg38
  metadata:
    batch: 020-20-batch
    phenotype: tumor
```
it had 
```
- algorithm:
    aligner: false
    mark_duplicates: false
    mixup_check: qsignature
    realign: false
    recalibrate: false
    variantcaller: false
  analysis: variant2
  description: 020-20
  files:
  - /path/to/ready.bam
  genome_build: hg38
  mixup_check: qsignature_full
  metadata:
    batch: 020-20-batch
    phenotype: tumor

```

**Comment by lpantano** [comment]
I guess your template was?, I am trying to reproduce this and see what is the problem:

```
- algorithm:
    aligner: false
    mark_duplicates: false
    mixup_check: qsignature
    realign: false
    recalibrate: false
    variantcaller: false
  analysis: variant2
  genome_build: hg38
```

thanks

**Comment by sluke123** [comment]
Actually I had the variantcaller as a list – perhaps it was that giving me a problem? If so please close the issue.


- algorithm:

    aligner: false

    mark_duplicates: false

    mixup_check: qsignature

    realign: false

    recalibrate: false

    variantcaller: [false]

  analysis: variant2

  genome_build: hg38

The sample yaml file then had mixup_check: qsignature in the algorithm section, and at the top level.


Sally Luke
Associate Principal Scientist
_____________________________________________________________________________________________
AstraZeneca
IT | R&D Information
2 Riverside, Granta Park, Great Abington, Cambridge CB21 6GH
M: +44 (0) 7818 523808

**Comment by mjafin** [comment]
Here's the template, it was run on bam files:
```
# Template for paired (tumor/normal) variant calling
# see http://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html for more options!
---
details:
  - analysis: variant2
    genome_build: hg38 # [hg19, GRCh37, mm10, rn5]
    mixup_check: qsignature_full
    # In order to do paired variant calling, samples should belong to the
    # same batch ("batch" under "metadata" below") and have a "phenotype"
    # field stating either "normal" or tumor". For each batch there
    # should be a sample with "tumor" phenotype and a sample with "normal"
    # phenotype (no more than two samples per batch)
    algorithm:
      aligner: false # [bwa, bowtie, bowtie2, mosaik, novoalign, false], set to false for targeted panels that use pcr
      mark_duplicates: false
      recalibrate: false  # [gatk, false]
      realign: false  # [gatk, gkno, false]
      mixup_check: qsignature
      variantcaller: [false] # Valid values are "mutect", "varscan", "freebayes", "vardict"

```
