### ISSUE TITLE
RNA-seq variant calling: how to run snpeff?

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1443]
Hi bcbio developers;

I'm running RNA-seq pipeline for variant calling with
```
details:
- algorithm:
    aligner: star
    effects: snpeff
    variantcaller: gatk
    merge_bamprep: true
  analysis: RNA-seq
  description: SRR307897
  files:
  - [somewhere]/input/SRR307897_1.fq
  - [somewhere]/input/SRR307897_2.fq
  genome_build: GRCh37
upload:
  dir: ../final
```
It seems that snpeff is not starting.
Could you please check this?

Many thanks!
SN
