### ISSUE TITLE
vardict output vcf in gzip

### ISSUE THREAD

**Issue by csardas** [chapmanb/bcbio-nextgen#1455]
I tried to use vardict to call variants in RNAseq analysis,
the final output gave me a SampleName-vcf.vcf file with strange character
the file is a gzip compressed file
and there is nothing special in log files

It seems there is something wrong on file name?
the file should be named as SampleName.vcf.gz

and can gemini process be called up with RNAseq variant calling? I cant find and .db file in the output

below is my config yaml

```
upload:
  dir: ./final
details:
- algorithm:
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: False
    fusion_mode: True
    variantcaller: vardict
  analysis: RNA-seq
  description: 525N_testrun14
  files:
  - ../525N_S99_L999_R1_001.clean.fastq.gz
  - ../525N_S99_L999_R2_001.clean.fastq.gz
  genome_build: GRCh37
```
