### ISSUE TITLE
Allow overriding Java binary in resources

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1492]
As MuTect 1 is not compatible with Java 8 (throws a lot of errors) I'd like to point the pipeline to a Java 7 version (the one installed systemwide). Setting

```yaml
resources:
    java:
        bin: /usr/bin/java
```

Has no effect, because the pipeline calls `java` directly, hence the first one picked up in PATH "wins".
