### ISSUE TITLE
Insufficient memory error during gatk joint genotyping

### ISSUE THREAD

**Issue by hliang** [chapmanb/bcbio-nextgen#1565]
I'm having an issue when trying to genotype all 160 whole genome samples (10X coverage each) together (by not specifying `joint_group_size` at all). Each compute nodes in our cluster have 24 cores + 64 G. I ran bcbio_nextgen with `-t ipython -n 480 -s slurm -q bcbio`. The HaplotypeCaller ran with `-Xms681m -Xmx3181m`, which went fine. GenotypeGVCFs ran with `-Xms500m -Xmx42998m` and `-nt 15` and complained about insufficient memory, then quit for most of the callable regions. Below is my resources section in samples.yaml

```
resources:
  default:
    cores: 24
    memory: 2500M
  gatk:
    dir: /path/to/bcbio/anaconda/opt/gatk-3.6-0-g89b7209/
    version: 3.6-0-g89b7209
  machine:
    cores: 24
    memory: 64
```
No `jvm_opts` was specified for gatk, so I think it pulled the default `jvm_opts: ["-Xms500m", "-Xmx3500m"]` from `/path/to/bcbio/galaxy/bcbio_system.yaml`.

I had tried to run a genotype command (which has `-nt 15`) in `log/bcbio-nextgen-commands.log` manually, and failed with the same `insufficient memory` error. However, if I try with single thread `-nt 1`, it would finish happily.

So I'm wondering what parameters I should set in order to let bcbio use single (or fewer) thread for GenotypeGVCFs?
