### ISSUE TITLE
Picard CreateSequenceDictionary out of memory when adding reference genome. 

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1569]
When trying to add a reference genome  to bcbio I get an out of memory error from Picard CreateSequenceDictionary. 

The reference that I am trying to add has a very high number of contigs. 

The picard memory arguments used are 
`picard -Xms500m -Xmx1g`

I don't find these memory setting back in the bcbio_system.yaml file
```
# default options, used if other items below are not present
  # avoids needing to configure/adjust for every program
  default:
    memory: 3G
    cores: 10
    jvm_opts: ["-Xms750m", "-Xmx3500m"]
  gatk:
    jvm_opts: ["-Xms500m", "-Xmx3500m"]
  snpeff:
    jvm_opts: ["-Xms750m", "-Xmx4g"]
  qualimap:
    memory: 4g
  express:
    memory: 8g
  dexseq:
    memory: 10g
  macs2:
    memory: 8g
  seqcluster:
    memory: 8g
```

I tried adding a specific picard entry to that file.
```
picard:
    jvm_opts: ["-Xms750m", "-Xmx5500m"]
```

But that option does not seem to be picked up for the picard CreateSequenceDictionary command. 

How can I best set a higher max memory for the picard CreateSequenceDictionary  command used for adding a reference genome?

I could run this picard comand by hand but I would like to make use of the automatic updating of the loc files that runs after this command.  This is probably not the last reference genome that I need to add which runs in to this max mem limit.
