### ISSUE TITLE
slowdown while calculating coverage bins

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1583]
Hi Brad,

We're experiencing a huge slowdown of the analysis while calculating the coverage bins.

Command executed:

```
[2016-09-30T08:44Z] /home/galaxy/bcbio/galaxy/../anaconda/bin/samtools depth -a -Q 1 -b /home/tsante/demultiplex/160714_J00178_0006_AHFKCCBBXX_allow1error/merged/EOG/work/align/D1402336/D1402336-sort-callable-split/D1402336-sort-X-callable-coverageregions.bed --reference /home/galaxy/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa /home/tsante/demultiplex/160714_J00178_0006_AHFKCCBBXX_allow1error/merged/EOG/work/align/D1402336/D1402336-sort.bam | /home/galaxy/bcbio/anaconda/bin/python -c 'import bcbio.bam.callable; bcbio.bam.highdepth.bin_depths(4, 1196, 250, "/tmp/bcbiotx/f2d69a2e-2c40-4be0-962b-655ba4429e60/tmpopyDhJ/D1402336-sort-X-callable.bed", "/tmp/bcbiotx/f2d69a2e-2c40-4be0-962b-655ba4429e60/tmpopyDhJ/D1402336-sort-X-highdepth.bed")'
```

bcbio startup command:

```
bcbio_nextgen.py /path/to/config.yaml -t local  -n 12
```

We designated 12 cores to bcbio, but we notice it's only using 4 during this step
bcbio-debug log:

```
[2016-09-30T03:15Z] Resource requests: ; memory: 1.00; cores: 1
[2016-09-30T03:15Z] Configuring 4 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-09-30T03:15Z] multiprocessing: calc_callable_loci
```

Any idea what could be causing this? As I see it, the speed could be tripled by using all available cores.

Thanks for the help.
M

**Comment by chapmanb** [comment]
Sorry about the issues, the coverage calculation should use all available cores assigned to a sample, but it sounds like you might have core usage in `bcbio_system.yaml` set to use 4 cores/sample, rather than 12. bcbio will partition total cores into the samples based on this setting:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html#tuning-core-and-memory-usage

So if you only have a single (or few samples) it'll underuse cores. If you set default cores to 12 in your `bcbio_system.yaml` file, hopefully this improves usage and speeds it up.

**Comment by matthdsm** [comment]
the thing is, we're doing a run with 48 samples. When we're using just one sample or something, bcbio just flies over this. I'm a bit lost. bcbio is running on a node with 16 cores and 32gb memory.
Our global config looks like this:

```
[pbsqueue] galaxy:galaxy $ cat bcbio_system.yaml                                                                                                                                                                                                                                                                    [8:36:45]
galaxy_config: /home/galaxy/galaxy-dist/config/galaxy.ini
resources:
  tmp:
    dir: /tmp
  bwa:
    cmd: bwa
    cores: 4
  cufflinks:
    cores: 4
    memory: 1g
  default:
    cores: 4
    jvm_opts:
    - -Xms750m
    - -Xmx2000m
    memory: 2G
  dexseq:
    memory: 10g
  express:
    memory: 8g
  freebayes:
    memory: 4g
  gatk:
    dir: /home/galaxy/bcbio/toolplus/gatk/3.6-0-g89b7209
  gemini:
    cores: 4
  hisat2:
    cores: 4
    memory: 2G
  macs2:
    cores: 1
    memory: 2G
  miraligner:
    jvm_opts:
    - -Xms750m
    - -Xmx4500m
  oncofuse:
    jvm_opts:
    - -Xms750m
    - -Xmx2000m
  picard:
    cores: 4
    jvm_opts:
    - -Xms750m
    - -Xmx2000m
  qualimap:
    memory: 2g
  sailfish:
    cores: 4
    memory: 1g
  samtools:
    cores: 4
    memory: 2G
  seqcluster:
    memory: 8g
  snap:
    cores: 6
    memory: 4G
  snpeff:
    cores: 4
    jvm_opts:
    - -Xms750m
    - -Xmx2000m
  star:
    cores: 4
    memory: 2g
  stringtie:
    cores: 4
    memory: 1g
  vardict:
    jvm_opts:
    - -Xms750m
    - -Xmx2000m
  vep:
    cores: 4
  wham:
    memory: 2000m
```


Any idea how we should tweak this to improve parallelization?

Thanks!
M
