### ISSUE TITLE
Variant calling not parallelized by split regions in WGS analysis

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1662]
I am running a 100-sample WGS batch with the `variant2` workflow and 

```
nomap_split_size: 250
nomap_split_targets: 200
variantcaller: vardict
```

I would expect that variant calling is parallelized also within a single sample by using the split regions (split at unmapped/N reference); however, that is not the case in my current run. Instead, the `vardict-java` pipe is applied on each full chromosome rather than on the mapped blocks in each chromosome. Is there any advice on how I can find out why that may be the case? 

Obviously, that limits scalability quiet a lot for me (especially since the limiting step in the `vardict` pipe is an R script, `teststrandbias.R`, which seems to take forever) and I was under the impression that parallelization by subregions still worked in my last largish WGS analysis 2 months ago. Thanks!

**Comment by mjafin** [comment]
Hi @schelhorn, I'll let Brad address the main question but I'd be interested in knowing if `teststrandbias.R` is taking time disproportionately vs. the Java main process? Usually it's been a tiny fraction so we haven't bothered optimising it further. If it's starting to be the bottle neck then we should definitely consider removing the R dependency and replace with faster code (c or Java).

**Comment by schelhorn** [comment]
if that helps, the `*-analysis_blocks.bed` files always contain the whole chromosomes, as do the `*-regions.bed` and `*-unmerged-regions.bed` files. The `*-unmerged-regions-glimit.bed` files contain subregions, but I believe these are only used within a `vardict` process, and not being used to start multiple such processes.

**Comment by schelhorn** [comment]
Thanks, @mjafin, for chiming in. Yes, the R process takes most of the CPU time in my 30x unpaired WGS cases. I would definitely be in favor of baking everything into the main `vardict` binary (the whole pipe is `vardict | teststrandbias.R | var2vcf_valid.pl | awk  | awk  | awk | vcfstreamsort | bgzip `).

**Comment by mjafin** [comment]
As a first step we'd probably be looking into developing a drop in replacement for the two strand bias testing functions and maybe in the longer term incorporating some parts in the java file. Let me bring this up internally.

**Comment by NeillGibson** [comment]
Hi,

I also have the same issue I think. My yaml:

```
# Template for whole genome Illumina variant calling with FreeBayes
# This is a GATK-free pipeline without post-alignment BAM pre-processing
# (recalibration and realignment)
---
details:
  - analysis: variant2
    genome_build: my_reference
    description:
    # to do multi-sample variant calling, assign samples the same metadata / batch
    metadata:
      batch: project_123
    algorithm:
      aligner: bwa
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: freebayes
      nomap_split_targets: 3000
      effects: false
      tools_off:
      - gemini
      # for targetted projects, set the region
      # variant_regions: /path/to/your.bed
resources:
    freebayes:
        options: [--genotype-qualities, --min-mapping-quality 20]
```

So  I request a max split of 3000 regions for variant calling but I get 13, 1 per chromosome. 
```
grep Identified log/bcbio-nextgen.log
[2016-11-30T01:03Z] node22: Identified 13 parallel analysis blocks
```

I can also confirm that only 13 vcf files are being produced.
