### ISSUE TITLE
Variant calling pipeline may produce misleading validation report because of GATK/bcftools issue at high coverage

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1671]
Hello!

It is not a problem of bcbio, but it might lead to the misleading validation reports like shown on the picture below. Something is wrong for gatk-haplotype and ensemble there.
![na12878-1-validate](https://cloud.githubusercontent.com/assets/13981803/20849119/275fa008-b8a3-11e6-9c06-904bdc9dfebb.png)
This is because of this issue:
https://github.com/samtools/bcftools/issues/504

Sergey

**Comment by chapmanb** [comment]
Sergey;
Thanks for identifying this issue, we'd definitely want to fix whatever is causing the poor GATK HaplotypeCaller results in this case. Are you generating this comparison with a public dataset I could reproduce and fix this with? I'm not sure how the bcftools issue you linked relates to the problem you're seeing. Could you expand a little so I could reproduce and fix this issue? Thanks much.

**Comment by naumenko-sa** [comment]
Hi Brad;

Sorry, I am not permitted to share the data, it is NA12878 exome with high coverage (165x). Let's debug remotely - I will check whatever you want.

I'm running this config:
```
---
upload:
  dir: ../final
details:
  - files: [../input/202214_1.fq, ../input/202214_2.fq]
    description: NA12878-1
    metadata:
      sex: female
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      align_split_size: 5000000
      variantcaller: [freebayes, gatk-haplotype, samtools, platypus]
      recalibrate: gatk
      realign: gatk
      validate: giab-NA12878/truth_small_variants.vcf.gz 
      validate_regions: giab-NA12878/truth_regions.bed
      variant_regions: ../input/S06588914_Covered.sort.merged.bed
      remove_lcr: true
      ensemble:
        numpass: 2
      clinical_reporting: true
      effects: vep
      tools_on: [svplots, qualimap]
  - files: [../input/202214_1.fq, ../input/202214_2.fq]
    description: NA12878-2
    metadata:
      sex: female
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      align_split_size: 5000000
      variantcaller: [freebayes, gatk-haplotype, samtools, platypus]
      recalibrate: gatk
      realign: gatk
      validate: giab-NA12878/truth_small_variants.vcf.gz 
      validate_regions: giab-NA12878/truth_regions.bed
      variant_regions: ../input/S06588914_Covered.sort.merged.bed
      remove_lcr: false
      ensemble:
        numpass: 2
      clinical_reporting: true
      effects: vep
      tools_on: [svplots, qualimap]
resources:
  default:
    memory: 10G
    cores: 5
    jvm_opts: ["-Xms750m", "-Xmx10000m"]
```

Then I go to work/validate/
`cat grading-summary-NA12878-1.csv | grep SNPs | grep tp`
```
NA12878-1,ensemble,SNPs,tp,18292
NA12878-1,freebayes,SNPs,tp,38453
NA12878-1,gatk-haplotype,SNPs,tp,5058
NA12878-1,samtools,SNPs,tp,38458
NA12878-1,platypus,SNPs,tp,38155
```

Something is wrong for gatk-haplotype and ensembl.

cd NA12878-1/gatk-haplotype/rtg
I assume that bcbio.variation.validate.py,
function _rtg_add_summary_file(eval_files, base_dir, data): uses bcftools.

`bcftools --version`
```
bcftools 1.3.1
Using htslib 1.3.1
```
`bcftools view --types snps tp-baseline.vcf.gz | grep -v "^#" | wc -l`
```
[tp-baseline.vcf.gz] Warning: no BGZF EOF marker; file may be truncated.
[E::vcf_parse_format] Invalid character '_' in 'PS' FORMAT field at 1:1254436
[E::vcf_parse_format] Invalid character '_' in 'PS' FORMAT field at 1:1254443
48
```
The PS field sometimes contains phasing information like **1254436_A_G**, which is not Integer:
`gunzip -c tp-baseline.vcf.gz | grep 1254436`
```
1	1254436	rs1886773	A	G	50	PASS	platforms=4;platformnames=Illumina,CG,10X,Solid;datasets=4;datasetnames=HiSeqPE300x,CGnormal,10XChromium,SolidSE75bp;callsets=5;callsetnames=HiSeqPE300xGATK,CGnormal,HiSeqPE300xfreebayes,10XGATKhaplo,SolidSE75GATKHC;datasetsmissingcall=IonExome,SolidPE50x50bp;callable=CS_HiSeqPE300xGATK_callable,CS_CGnormal_callable,CS_HiSeqPE300xfreebayes_callable;filt=CS_SolidSE75GATKHC_filt	GT:PS:DP:ADALL:AD:GQ	1|1:1254436_A_G:577:0,241:99,336:499
1	1254443	rs1886772	G	A	50	PASS	platforms=4;platformnames=Illumina,CG,10X,Solid;datasets=4;datasetnames=HiSeqPE300x,CGnormal,10XChromium,SolidSE75bp;callsets=5;callsetnames=HiSeqPE300xGATK,CGnormal,HiSeqPE300xfreebayes,10XGATKhaplo,SolidSE75GATKHC;datasetsmissingcall=IonExome,SolidPE50x50bp;callable=CS_HiSeqPE300xGATK_callable,CS_CGnormal_callable,CS_HiSeqPE300xfreebayes_callable;filt=CS_SolidSE75GATKHC_filt	GT:PS:DP:ADALL:AD:GQ	1|1:1254436_A_G:584:0,245:98,338:476
```
When I set Type=String for PS field, it starts working:
`cat tp-baseline.vcf | grep "ID=PS"`
```
##FORMAT=<ID=PS,Number=1,Type=String,Description="Phase set in which this variant falls">
```
`bcftools view --types snps tp-baseline.vcf | grep -v "^#" | wc -l`
`38446`

This variant comes from 
tools/bcbio/genomes/Hsapiens/GRCh37/validation/giab-NA12878
`gunzip -c truth_small_variants.vcf.gz | grep 254436_A_G`
```
1	1254436	rs1886773	A	G	50	PASS	platforms=4;platformnames=Illumina,CG,10X,Solid;datasets=4;datasetnames=HiSeqPE300x,CGnormal,10XChromium,SolidSE75bp;callsets=5;callsetnames=HiSeqPE300xGATK,CGnormal,HiSeqPE300xfreebayes,10XGATKhaplo,SolidSE75GATKHC;datasetsmissingcall=IonExome,SolidPE50x50bp;callable=CS_HiSeqPE300xGATK_callable,CS_CGnormal_callable,CS_HiSeqPE300xfreebayes_callable;filt=CS_SolidSE75GATKHC_filt	GT:PS:DP:ADALL:AD:GQ	1|1:1254436_A_G:577:0,241:99,336:499
1	1254443	rs1886772	G	A	50	PASS	platforms=4;platformnames=Illumina,CG,10X,Solid;datasets=4;datasetnames=HiSeqPE300x,CGnormal,10XChromium,SolidSE75bp;callsets=5;callsetnames=HiSeqPE300xGATK,CGnormal,HiSeqPE300xfreebayes,10XGATKhaplo,SolidSE75GATKHC;datasetsmissingcall=IonExome,SolidPE50x50bp;callable=CS_HiSeqPE300xGATK_callable,CS_CGnormal_callable,CS_HiSeqPE300xfreebayes_callable;filt=CS_SolidSE75GATKHC_filt	GT:PS:DP:ADALL:AD:GQ	1|1:1254436_A_G:584:0,245:98,338:476
```
I may assume that with such a high coverage (165X), the algorithms is able to call these variants.
In the standard bcbio WES validation (44x) they are absent:

`gunzip -c tp-baseline.vcf.gz | grep -c rs1886773`
```0```

Sergey
