### ISSUE TITLE
cutadapt hangs when input is fastq.gz

### ISSUE THREAD

**Issue by stephenturner** [chapmanb/bcbio-nextgen#1700]
Trying to run the small rna-seq pipeline with a template that looks like this:

```
upload:
  dir: ../final
details:
  - analysis: smallRNA-seq
    algorithm:
      aligner: star
      # change adapter according project
      adapters: ["TGGAATTCTCGGGTGC"]
      expression_caller: [trna, seqcluster, mirdeep2]
      species: mmu
    genome_build: mm10
```

Runs for days at the trimming step:

```
[2016-12-16T14:56Z] /path/share/bcbio/anaconda/bin/cutadapt --adapter=TGGAATTCTCGGGTGC --untrimmed-output=/path/work/trimmed/wt4/wt4.fragments.fastq.gz -o /path/work/trimmed/wt4/tx/tmpSWigfG/wt4.clean.fastq.gz -m 17 --overlap=8 /path/wt4.fastq.gz --too-short-output /path/work/trimmed/wt4/wt4.short.fastq.gz | tee > /path/work/trimmed/wt4/wt4.log
```

I tried this command directly at the command line, and it hangs forever without doing anything. Then gunzip'd the input file (also didn't gz the outputs) and it worked fine.

Possibly related to marcelm/cutadapt#137?
