### ISSUE TITLE
Question regarding coverage_depth_min and min_allele_fraction

### ISSUE THREAD

**Issue by Wixaros** [chapmanb/bcbio-nextgen#1776]
Hi again.

Thanks for the previous help! The pipeline is now running and we have tested a lot of stuff. However I came across something. We have a project with targeted sequencing of 10 tumors (tumor only from FFPE). We were thinking of using the provided here (http://bcb.io/2015/03/05/cancerval/). However, when we try to set the `coverage_depth_min` and `min_allele_fraction` to some values, our prioritized vcf file contains passed variants with a read depth of eg. 100 while `coverage_depth_min` is set to 300. We are using the following setup:

```
details:
- algorithm:
    aligner: false
    mark_duplicates: false
    realign: false
    recalibrate: false
    variant_regions: /pathway/to/region/BED/BED_region_file_.bed
    variantcaller: [freebayes]
    indelcaller: false
    effects: vep
    coverage_depth_min: 300
    min_allele_fraction: 5
  analysis: variant2
  description: Sample1
  files:
  - /pathway/to/bam/Sample1.bam
  genome_build: GRCh37
  metadata:
    phenotype: tumor
    sex: female
```

We have already aligned the bam files with novoalign, so we are just interested in the variantcaller. One SNV looks like this: 
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Sample1
3	37058918	.	A	G	905.73	PASS	AB=0.56338;ABP=5.48761;AC=1;AF=0.5;AN=2;AO=40;CIGAR=1X;DP=71;DPB=71;DPRA=0;EPP=4.96463;EPPR=11.486;GTI=0;LEN=1;MEANALT=1;MQM=59.525;MQMR=60;NS=1;NUMALT=1;ODDS=90.3702;PAIRED=0.95;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=1366;QR=834;RO=31;RPL=6;RPP=45.5712;RPPR=70.3259;RPR=34;RUN=1;SAF=29;SAP=20.5992;SAR=11;SRF=21;SRP=11.486;SRR=10;TYPE=snp;technology.ILLUMINA=1;CSQ=intron_variant|||ENSG00000076242|MLH1|ENST00000231790||||-/756|protein_coding|YES|CCDS2663.1|||,intron_variant&NMD_transcript_variant|||ENSG00000076242|MLH1|ENST00000413212||||-/52|nonsense_mediated_decay|||||,intron_variant|||ENSG00000076242|MLH1|ENST00000435176||||-/658|protein_coding||CCDS54562.1|||,intron_variant|||ENSG00000076242|MLH1|ENST00000441265||||-/105|protein_coding|||||,intron_variant&NMD_transcript_variant|||ENSG00000076242|MLH1|ENST00000447829||||-/58|nonsense_mediated_decay|||||,intron_variant|||ENSG00000076242|MLH1|ENST00000455445||||-/515|protein_coding||CCDS54563.1|||,intron_variant|||ENSG00000076242|MLH1|ENST00000456676||||-/679|protein_coding|||||,downstream_gene_variant|||ENSG00000076242|MLH1|ENST00000457004||||-/38|nonsense_mediated_decay|||||,intron_variant&NMD_transcript_variant|||ENSG00000076242|MLH1|ENST00000458009||||-/95|nonsense_mediated_decay|||||,intron_variant|||ENSG00000076242|MLH1|ENST00000458205||||-/515|protein_coding||CCDS54563.1|||,upstream_gene_variant|||ENSG00000224858|RPL29P11|ENST00000494408|||||processed_pseudogene|YES||||,intron_variant|||ENSG00000076242|MLH1|ENST00000536378||||-/460|protein_coding|||||,intron_variant|||ENSG00000076242|MLH1|ENST00000539477||||-/515|protein_coding||CCDS54563.1|||,upstream_gene_variant|||ENSG00000224858|RPL29P11|ENST00000600290|||||processed_pseudogene|||||;EPR=pass,clinvar,lowseverity	GT:GQ:DP:RO:QR:AO:QA:GL	0/1:160:71:31:834:40:1366:-101.801,0,-53.9493
```

The DP signal states a value of 71, which shouldn't pass the filter set to 300? Are we doing something wrong, or is it simply because we have tumor only samples and that some other conditions are taking precedence? 

Thank you for a very nice work with the bcbio!

Best

Nicolai
