### ISSUE TITLE
validate regions

### ISSUE THREAD

**Issue by rjsicko** [chapmanb/bcbio-nextgen#1824]
I'm trying to determine why the validation numbers in bcbio look different than numbers I get from running rtg vcfeval on my own.

I'm running the variant2 analysis on TrueSeq custom amplicon data and validating against NA12878 GIAB. I've figured out I was using an older version of GIAB (I was using 3.3 and bcbio is using 3.3.1) which accounted for some of the difference. I think the --bed-regions file bcbio is using is accounting for the majority of differences. I was using my targets.bed and it looks like bcbio is using a bed file it generates from a callable regions bed. This does seem like a better way, I'm just trying to figure out how the callable regions are calculated.

**sample yaml**
````
upload:
  dir: ../final
details:
  - files: [../input/12_S12_L001_R1_001.fastq.trim.fastq, ../input/12_S12_L001_R2_001.fastq.trim.fastq]
    description: NA12878-1
    metadata:
      sex: female
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      variantcaller: [freebayes, gatk-haplotype, samtools]
      mark_duplicates: false
      recalibrate: false
      realign: false
      coverage_interval: amplicon
      validate: giab-NA12878/truth_small_variants.vcf.gz
      validate_regions: giab-NA12878/truth_regions.bed
      variant_regions: ../input/SCIDv2-2_targets_sorted_no_chr.bed
      coverage: ../input/170213_SCID_Exons_w_20bp_Padding.sorted.b37.bed
      ensemble:
        numpass: 2
````
