### ISSUE TITLE
using globals in vcfanno custom conf

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1860]
Hi Brad,

I've been trying to use values from `globals` in the `vcfanno`option
e.g. 
```
globals:
  - eog: path/to/eog.conf
  - jpopgen: path/to/jpopgen.conf
vcfanno: [gemini,eog,jpopgen]
```

When using the `global` options, bcbio goes looking for a likewise named file in `genomes/hsapiens/hg38/vcfanno`

Is it possible to build in a check for `globals`?

Thanks
M
