### ISSUE TITLE
pipeline for calling variants from exome data using hg38

### ISSUE THREAD

**Issue by mce1** [chapmanb/bcbio-nextgen#1877]
Dear Brad,

sorry to bother you with this, but I seem to be unable to get a bcbio pipeline to work and wondered if you could maybe help.

What I'd like to do is call variants from exome data using the hg38 genome build. I have started with the getting started - example pipeline - NA12878-exome-methodcmp.yaml as provided on the website (i.e. specifying genome_build GRCh37), which seems to work fine both for the test data you supply and for my own data. [To be entirely correct, I get one error message ("gzip: stdout: Broken pipe", same as line 19 in the stderr.txt file attached) but the script completes, and the vcf files look reasonable, so I think/hope that this is not a major problem.]

Next thing, I'd like to do the same using the hg38/GRCh38 genome build. I have run bcbio_nextgen_install.py specifiying hg38 (and the aligners I would like to use), which completed successfully. I have modified the config.yaml file as below/attached.

```
---
upload:
  dir: ../final
details:
  - files: [../input/person-1299.fq.gz]
    description: person-1299-exome
    metadata:
      sex: male
    analysis: variant2
    genome_build: hg38
    algorithm:
      aligner: bwa
      variantcaller: [freebayes, gatk-haplotype, samtools]
      recalibrate: gatk
      realign: gatk
      ensemble:
        numpass: 2
```

However, the pipeline terminates with an IOerror just after the bwa alignment step, probably while checking coverage. Standard output says:

```
An unexpected error occurred while tokenizing input file /home/mce/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.pyc
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (25, 0))

An unexpected error occurred while tokenizing input file /home/mce/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/coverage.pyc
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (5, 0))

```

I seem to be unable to figure out what the actual problem is here and was wondering if you could maybe have a look. I have attached the .yaml file as well as the output to stdout and stderr.

Your help would be much appreciated,

mce1

[exome-hg38-ensembl.yaml.txt](https://github.com/chapmanb/bcbio-nextgen/files/868409/exome-hg38-ensembl.yaml.txt)

[stderr.txt](https://github.com/chapmanb/bcbio-nextgen/files/868411/stderr.txt)

[stdout.txt](https://github.com/chapmanb/bcbio-nextgen/files/868413/stdout.txt)
