### ISSUE TITLE
request: copy "raw" cnvkit output to final

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1890]
Hi Brad,
ping @etal 

We're looking into moving our CNVseq pipeline to bcbio using CNVkit. However, the cnvkit output that can be used to create the plots isn't copied to the `final` dir.

Our current config looks like this:
```
#bcbio-nextgen v1.0.2
---
#include an experiment name here
fc_name:
upload:
  dir: ../final
resources:
  tmp:
    dir: /tmp/bcbio
details:
  - analysis: variant2
    genome_build: hg38
    description:
    metadata:
      batch:
    algorithm:
      aligner: bwa
      save_diskspace: true
      coverage_interval: regional
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: false
      svcaller: cnvkit
    # add the path to your files here
    files:
```

Is this a configuration issue or just an oversight in bcbio?

Thanks 
M

PS; we don't need snp variant calling, just the structural variants as these analyses are run on low coverage WGS samples.
