### ISSUE TITLE
Possible memory leak in bcbio_nextgen.py

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1918]
Hi Brad,

We're experiencing a somewhat weird issue.
We run bcbio with iPython on a torque cluster, where the bcbio_nextgen.py command is run as a single core job, which then spawns the iPython jobs.
This "master" job seems to be using an excessive amount of memory, which keep rising untill the worker node runs out and the job is killed. 

Any idea what could be causing this? Currently, the memory usage is stable at about 8Gb, which seems to be a tad too much I think.

Thanks
M

**Comment by roryk** [comment]
Hi Matthias,

Which pipeline are you seeing this behavior?

**Comment by matthdsm** [comment]
Just the default "variant2" pipeline. We're using v1.02 with the following config
```
#bcbio-nextgen v1.0.2
---
#include an experiment name here
fc_name:
upload:
  dir: ../final
globals:
  analysis_regions: RefSeq_allexons_20bp.sorted.merged.bed
resources:
  tmp:
    dir: /tmp/bcbio
details:
  - analysis: variant2
    genome_build: hg38
    description:
    metadata:
      batch:
    algorithm:
      aligner: bwa
      save_diskspace: true
      coverage_interval: regional
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      variant_regions: analysis_regions
      jointcaller: gatk-haplotype-joint
      effects: vep
      effects_transcripts: all
      vcfanno: [gemini,../config/eog.conf,../config/jpopgen.conf]
      tools_on:
        - vep_splicesite_annotations
      # add the path to your files here
      files:
```

Thanks for looking into this.
M
