### ISSUE TITLE
no gemini db created

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1992]
Hi Brad,

just a quick question,
Did something change that could affect the creation of the gemini db's using vcf2db? On our last 2 runs, using the latest dev code, no db's were created. I went through the command logs, and I saw the script was never called during the pipeline.

run config:
```
details:
- algorithm:
    aligner: bwa
    coverage_interval: regional
    effects: vep
    effects_transcripts: all
    jointcaller: gatk-haplotype-joint
    mark_duplicates: true
    realign: false
    recalibrate: false
    save_diskspace: true
    tools_on:
    - vep_splicesite_annotations
    variant_regions: analysis_regions
    variantcaller: gatk-haplotype
    vcfanno:
    - gemini
    - ../config/eog.conf
    - dbscsnv
    - dbnsfp
  analysis: variant2
  description: D1701453
  files:
  - /home/projects/bcbio_annotation/exomes/HSQExomes/hg38/HSQ_RUN_026/input/D1701453_R1.fastq.gz
  - /home/projects/bcbio_annotation/exomes/HSQExomes/hg38/HSQ_RUN_026/input/D1701453_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: null
fc_date: '2017-06-20'
fc_name: HSQ_026
globals:
  analysis_regions: /home/projects/bcbio_annotation/ref/variant_regions/RefSeq_allexons_20bp.sorted.merged.bed
resources:
  tmp:
    dir: /tmp/bcbio
upload:
  dir: ../final
```

Any idea?
Thanks!
M
