### ISSUE TITLE
GATK4 variant_index_type is not a recognized option

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#2007]
Hi Brad, 

Thank you for evaluating GATK4 Engine-beta1 and making it already available in bcbio 1.0.4.

We are exited about being able to use GATK4 for incremental variant calling and also would like to evaluate it.

I run in to the following error when I try to run GATK4 Engine-beta1 in bcbio-1.0.4. on a small test data set of 8 existing BAM files / samples. 

`A USER ERROR has occurred: variant_index_type is not a recognized option`

The YAML I used is based on our existing freebayes YAML updated with gatk4 information from https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#variant-calling

```
# Template for whole genome Illumina variant calling with FreeBayes
# This is a GATK-free pipeline without post-alignment BAM pre-processing
# (recalibration and realignment)
---
details:
  - analysis: variant2
    genome_build: my_species
    description:
    # to do multi-sample variant calling, assign samples the same metadata / batch
    metadata:
      batch: DA-834_GATK
    algorithm:
      aligner: false
      mark_duplicates: false
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
      ploidy:
          default: 2
      nomap_split_targets: 3000
      effects: false
      tools_on: [gatk4,gvcf]
      tools_off:
      - gemini
      # for targetted projects, set the region
      # variant_regions: /path/to/your.bed
```

Is this a correct YAML for running GATK4 incremental variant calling where also the intermediary gVCF files are saved (so they can be reused later)?

The GATK4 command that bcbio-1.0.4. is trying to run is 
```
CalledProcessError: Command 'set -o pipefail;
unset JAVA_HOME &&
export PATH=/data/prod/Tools/bcbio/1.0.4/anaconda/bin:$PATH &&
gatk-launch --javaOptions '-Xms681m -Xmx3181m -XX:+UseSerialGC 
-Djava.io.tmpdir=/data/run/Projects/test_bcbio_1.0.4_gatk/DA_834_bam_table/work/bcbiotx/tmpaK6fWH' 
HaplotypeCaller 
-R /data/prod/Tools/bcbio/1.0.4/genomes/my_species/my_species/seq/my_species.fa 
--annotation BaseQualityRankSumTest --annotation FisherStrand --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth 
--annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation MappingQuality --annotation ClippedBases --annotation DepthPerAlleleBySample --annotation Coverage 
-I /data/run/Projects//test_bcbio_1.0.4_gatk/DA_834_bam_table/work/prealign/DA_342_05/DA_342_05-ready.bam 
-L /data/run/Projects//test_bcbio_1.0.4_gatk/DA_834_bam_table/work/gatk-haplotype/Chr_05/DA_342_05-Chr_05_3238319_3558575-regions.bed 
--interval_set_rule INTERSECTION --annotation ClippingRankSumTest --annotation DepthPerSampleHC 
--output /data/run/Projects//test_bcbio_1.0.4_gatk/DA_834_bam_table/work/bcbiotx/tmpDExSUa/DA_342_05-Chr_05_3238319_3558575.vcf.gz 
-ploidy 2 --emitRefConfidence GVCF 
--variant_index_type LINEAR 
--variant_index_parameter 128000 -GQB 10 -GQB 20 -GQB 30 -GQB 40 -GQB 60 -GQB 80
```

If I run the GATK4 Engine-beta1 jar myself with the haplotype caller command I also don't see the variant_index_type and variant_index_parameter parameters listed. 

Can it be that the variant_index_type and variant_index_parameter are somehow added by mistake (or by me using a wrong yaml)? 

Thank you!
