### ISSUE TITLE
issue using custom vcfanno config with relative path

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#2031]
Hi Brad,

Hope you had a good time at BOSC. Unfortunately, I was not able to attend.
I've encountered a small error when specifying multiple vcfanno config files.
I'm using a config like so:
```
#bcbio-nextgen v1.0.4 stable
---
#include an experiment name here
fc_name: bcbio_D1506290
upload:
  dir: ../final
globals:
  analysis_regions: /variant_regions/RefSeq_allexons_20bp.sorted.merged.bed
resources:
  tmp:
    dir: /tmp/bcbio
details:
  - analysis: variant2
    genome_build: hg38
    description: D1506290
    algorithm:
      aligner: bwa
      save_diskspace: true
      coverage_interval: regional
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      variant_regions: analysis_regions
      jointcaller: gatk-haplotype-joint
      effects: vep
      effects_transcripts: all
      vcfanno: [gemini,dbscsnv,dbnsfp,../conf/eog.conf]
      tools_on:
        - vep_splicesite_annotations
    # add the path to your files here
    files:
      - ../input/D1506290_R1.fastq.gz
      - ../input/D1506290_R2.fastq.gz
```

after which the log report this:
```
[2017-08-03T07:26Z] The vcfanno configuration /bcbio/genomes/Hsapiens/hg38/config/vcfanno/eog.conf.conf was not found for hg38, skipping.
```

It seems to me like bcbio didn't pick up the fact I was specifying a relative path to a custom config instead looking in the default location. I seem to recall this issue had already been fixed in the past. Did anything change regarding this? Or should I put the configs in a different order?

Thanks
M
