### ISSUE TITLE
What is the source of errors in the output bam file - recalibration?

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#2059]
Hello, bcbio devs and users!

Not a real issue, just to document this.

A typical resulting bam file produced by
```
details:
- algorithm:
    aligner: bwa
    mark_duplicates: true
    realign: true
    recalibrate: true
  analysis: variant2
  genome_build: GRCh37
```
is ok when checked by
```
samtools quickcheck -vvvv file.bam
verbosity set to 4
checking 1122R_163794.bam
opened 1122R_163794.bam
1122R_163794.bam is sequence data
1122R_163794.bam has 84 targets in header.
1122R_163794.bam has good EOF block.
```

and has some errors as reported by picard:
```
picard ValidateSamFile I=1122R_163794.bam MODE=SUMMARY
## HISTOGRAM	java.lang.String
Error Type	Count
ERROR:MATES_ARE_SAME_END	149593
ERROR:MATE_NOT_FOUND	238010
ERROR:MISMATCH_FLAG_MATE_UNMAPPED	299186
ERROR:MISMATCH_MATE_ALIGNMENT_START	36
ERROR:MISMATCH_MATE_CIGAR_STRING	299256
```

While it is ok to have some <300K reads with flag errors when the total amount is 50-100M,
what is the source of those flag errors? Is it realignment/recalibration/mark_duplication?

Thanks!
Sergey
