### ISSUE TITLE
PBS/torque overscheduling during variant calling

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#2101]
Hi Brad,

We've encountered a small bug in the iPython job scheduling during variant calling.
We have 4 nodes of each 16 cores, of which bcbio can use 3, with a manual restriction of 10 cores/node.

All of this works beautifully in all steps ( iPython submits 3 worker jobs asking 10 cores each) except for during variant calling. For some reason, there are always 4 worker jobs submitted, asking 10 cores each. This hasn't really bothered us before, but we're having some extra workload lately, and need those 10 extra cores available at all times.

Could this be some kind of error/typo in the configuration?

For completeness:
submit command: ` bcbio_nextgen.py conf.yaml -t ipython -n 30 -s torque -q default --timeout 30 --retries 3 --local_controller `

bcbio_system.yaml:
```
resources:
  # default options, used if other items below are not present
  # avoids needing to configure/adjust for every program
  machine:
    memory: 30
    cores: 10
  default:
    memory: 2G
    cores: 10
    jvm_opts: ["-Xms750m", "-Xmx2000m"]
  gatk:
    jvm_opts: ["-Xms500m", "-Xmx2000m"]
```

Cheers
M
