### ISSUE TITLE
Grabix index error with gzipped fastq

### ISSUE THREAD

**Issue by gabeng** [chapmanb/bcbio-nextgen#2106]
With the current development version I get a grabix error when starting from plain gzipped fastq files:

```
[grabix] .../work/bcbiotx/tmpzBTp94/X_S45_R1_001.fastq.gz doesn't exist or wasn't compressed with bgzip
```
The same files run nicely with bcbio 1.0.3. I noticed a lot of changes in alignprep since 1.0.3. The grabix command is the first executed in `bcbio-nextgen-commands.log`. This looks quite different in bcbio 1.0.3.
Any hints?

**Comment by gabeng** [comment]
I downgraded to bcbio 1.0.5 and the same error appears. Everything works fine with bcbio 1.0.3, the latest other version that I have at hand.

**Comment by gabeng** [comment]
Brad,
thanks for the quick response. Unfortunately, I do not know how these files were produced. They seem to be valid gzip archives, though. The command above returns `no`.
I will check this with files that I created myself and share them with you if I can reproduce it.

**Comment by chapmanb** [comment]
Ben -- that's unexpected, the first step should be re-bgzipping them if `grabix check` reports `no`. Could you also share your configuration? There is logic around handling remote files and other special cases and maybe there is some faulty logic with the checks there for your situation. Thanks much for the help debugging.

**Comment by gabeng** [comment]
I used the automated sample configuration using these templates:
bcbio.yaml:
```
---
details:
  - analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      coverage_interval: regional
      mark_duplicates: true
      recalibrate: false
      realign: false
      align_split_size: false
      effects: false
      variantcaller: [freebayes]
      tools_on: [bwa-mem]
      tools_off: [gemini]
      mixup_check: qsignature_full
      save_diskspace: true
upload:
  method: filesystem
  dir: final
resources:
  default:
    memory: 3G
    cores: 32
    jvm_opts: ["-Xms1000m", "-Xmx2000m"]
  samtools:
    cores: 32
    memory: 3G
  gatk-framework:
    jvm_opts: ["-Xms1000m", "-Xmx2000m"]
```
Project.csv sheet:
```
samplename,description,batch,phenotype,sex,variant_regions,coverage
X_S45,,,,config/enrichment_kit_106_padded.bed,config/enrichment_kit_106.bed
```

**Comment by gabeng** [comment]
The comands log shows this line to be executed first. The temporary directory is empty, though. Not sure if `grabix` is complaining about a missing file or about the compression.
```
[2017-10-15T18:50Z] /home/<user>/local/share/bcbio/galaxy/../anaconda/bin/grabix index /bioinf-data/Project/work/bcbiotx/tmp_j5lKk/X_S45_R1_001.fastq.gz
```

**Comment by chapmanb** [comment]
Thanks Ben -- it would also be helpful to see what the `files` attribute looks like in your generated YAML. That might help me read through the code and see if we're triggering any unexpected corners we shouldn't be. Thanks again for the help debugging.

**Comment by gabeng** [comment]
I did not retain the YAML at first, but quickly re-ran the job. Thanks for following up on this so quickly. This is the generated YAML:
```
details:
- algorithm:
    align_split_size: false
    aligner: bwa
    coverage: ../config/enrichment_kit_106.bed
    coverage_interval: regional
    effects: false
    mark_duplicates: true
    mixup_check: qsignature_full
    realign: false
    recalibrate: false
    save_diskspace: true
    tools_off:
    - gemini
    tools_on:
    - bwa-mem
    variant_regions: ../config/enrichment_kit_106_padded.bed
    variantcaller:
    - freebayes
  analysis: variant2
  description: X_S45
  files:
  - /bioinf-data/input/01_fastq/X_S45_R1_001.fastq.gz
  - /bioinf-data/input/01_fastq/X_S45_R2_001.fastq.gz
  genome_build: GRCh37
  metadata: {}
fc_name: 2017-10-15-18-37-50-603_grch37_1508092670603_bcbio
resources:
  default:
    cores: 32
    jvm_opts:
    - -Xms1000m
    - -Xmx2000m
    memory: 3G
  gatk-framework:
    jvm_opts:
    - -Xms1000m
    - -Xmx2000m
  samtools:
    cores: 32
    memory: 3G
upload:
  dir: final
  method: filesystem
```
