### ISSUE TITLE
Second alignment with UMI is not performed at all

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#2117]
Example configuration:

```yaml
- algorithm:
    aligner: bwa
    coverage: my_regions
    effects: vep
    effects_transcripts: canonical
    mark_duplicates: true
    min_allele_fraction: 1
    platform: illumina
    quality_format: Standard
    realign: false
    recalibrate: gatk
    remove_lcr: true
    trim_reads: false
    umi_type: fastq_name
    variant_regions: my_regions
    variantcaller:
        somatic: mutect2
  analysis: variant2
  description: 21557_test_umi
  files:
  - test-umi-fastq/21557_test_R1.fq.gz
  - test-umi-fastq/21557_test_R2.fq.gz
  genome_build: hg19
```

As part of the alignment run, first a file called `21557_test_umi-sort.bam` is created, then UMIs are processed regularly, creating `21557_blood_umi-test-cumi-1.fq.gz` and `21557_test_umi-sort-cumi-1.fq.gz`. However, then the code does, when realigning again:

```python
f1, f2 = postalign.umi_consensus(data)
del data["config"]["algorithm"]["umi_type"]
data["config"]["algorithm"]["mark_duplicates"] = False
data = align_to_sort_bam(f1, f2, aligner, data)
```
If we follow the chain in `align_to_sort_bam` we end up in `align_pipe` where:

```python
out_file = os.path.join(align_dir, "{0}-sort.bam".format(names["lane"]))
```

Which corresponds to `21557_test_umi-sort.bam` and then we check for existence:

```python

if not utils.file_exists(out_file):
    umi_ext = "-cumi" if "umi_bam" in data else ""
    out_file = os.path.join(align_dir, "{0}-sort{1}.bam".format(dd.get_sample_name(data), umi_ext))
```

but the file **does** exist, so this part is skipped (and so the alignment), and the result is that no `-cumi` files are generated at all. At least that's my understanding, since I checked the logs and the second BWA run is never done.

This configuration is part of a batch with 2 paired samples which I need to use for somatic variant calling. A single batch I did a few days earlier (but I don't remember if I updated) ran fine.
