### ISSUE TITLE
Tumour-only prioritization not working

### ISSUE THREAD

**Issue by ameynert** [chapmanb/bcbio-nextgen#2177]
v1.0.6, YAML file template:

```
details:
- algorithm:
    aligner: bwa
    background: /path/to/bcbio/genomes/Hsapiens/hg38/variation/1000G_omni2.5.vcf.gz
    platform: illumina
    quality_format: standard
    umi_type: fastq_name
    mark_duplicates: true
    recalibrate: true
    realign: false
    remove_lcr: true
    mixup_check: qsignature
    kraken: minikraken
    variantcaller: [vardict, mutect2, freebayes]
    min_allele_fraction: 5
    indelcaller: false
    ensemble:
      numpass: 2
      use_filtered: false
    effects: vep
    effects_transcripts: canonical
    tools_off: [gemini]
    tools_on: [damage_filter]
  analysis: variant2
  genome_build: hg38
upload:
  dir: /path/to/upload
```

Identical template YAML used under v1.0.5 and v1.0.6. In v.1.0.5, 16 panel sequenced samples resulted in 80 candidate somatic variants after tumour-only prioritization. The next set of 16 samples were processed under v1.0.6 and resulted in 2019 samples. Another 32 samples produced 6301 variants. Looking at the VCFs, the vast majority of variants are common - they have rsids and MAFs over 0.01 in the populations used by VEP.

**Comment by chapmanb** [comment]
Alison;
Thanks for the report and sorry about the issue. Prioritization needs to have the sample labelled as tumor to run, so this config would need to have:
```
metadata:
  phenotype: tumor
```
added, and then it should correctly run it. You could add this and run your previous samples in place to get this added to them. Let us know if you run into any other issues.

**Comment by ameynert** [comment]
Sorry, should have included that the phenotype info is added via the config file preparation step. The final config file looks like this:

```
details:
- algorithm:
    aligner: bwa
    background: /path/to/bcbio/genomes/Hsapiens/hg38/variation/1000G_omni2.5.vcf.gz
    effects: vep
    effects_transcripts: canonical
    ensemble:
      numpass: 2
      use_filtered: false
    indelcaller: false
    kraken: minikraken
    mark_duplicates: true
    min_allele_fraction: 5
    mixup_check: qsignature
    platform: illumina
    quality_format: standard
    realign: false
    recalibrate: true
    remove_lcr: true
    tools_off:
    - gemini
    tools_on:
    - damage_filter
    umi_type: fastq_name
    variant_regions: /path/to/targets/AZ-IDT_my-targets.hg38.bed
    variantcaller:
    - vardict
    - mutect2
    - freebayes
  analysis: variant2
  description: '9322'
  files:
  - /path/to/fastq/9322_R1.fastq.gz
  - /path/to/fastq/9322_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: 2017-12-01.100ng
    phenotype: tumor
    sex: female
fc_date: '2017-12-01.100ng'
fc_name: 2017-12-01.100ng
upload:
  dir: /path/to/upload
```

I noticed my install was missing the ExAC VCF, so I'm re-running upgrade -u stable with all the possible datatargets and will try again after that.
