### ISSUE TITLE
variant2pipeline workflow not marking duplicates?

### ISSUE THREAD

**Issue by cbrueffer** [chapmanb/bcbio-nextgen#2188]
Hi everyone,

the variant2pipeline workflow does not mark duplicates after alignment. I noticed this with bcbio-nextgen 1.0.2, and verified it with 1.0.6.

The config template I use is as follows (duplication marking is explicitly enabled):

```
details:
  - analysis: variant
    genome_build: hg38
    algorithm:
      # alignment
      platform: Illumina
      strandedness: firststrand
      aligner: hisat2
      mark_duplicates: true
      trim_reads: false
      recalibrate: false
      realign: false
      # variant calling
      variantcaller: [vardict]
      remove_lcr: false
      min_allele_fraction: 2
      effects: false
```

The workflow calls ```pipeline.sample.postprocess_alignment()```, where I would have expected duplicate marking to take place, but it's currently missing.

Is this intentional, or did I miss something obvious?
