### ISSUE TITLE
Question about ensemble vcfs 

### ISSUE THREAD

**Issue by tb08** [chapmanb/bcbio-nextgen#2196]
Hello Brad et al.,
I am using bcbio v1.07a, ensemble tumor only variant calling. I noticed that the ensemble vcf in the final upload directory:

> final/2017-12-20_PROJECT/mysample-ensemble-annotated.vcf.gz

 is not the latest one from the pipeline:

> work/ensemble/mysample/mysample-ensemble-vepeffects.vcf.gz

but instead matches this one:

>  work/ensemble/mysample/mysample-ensemble.vcf.gz

which also contains vep annotations but the ones from before the decomposition of variants. I suspect this is not the intended behaviour?
Moreover, when I look in the mysample-ensemble-vepeffects.vcf there is a small formatting problem as there is a missing semicolon in the INFO field between CALLERS and the next INFO, for example:

> BaseQRankSum=-0.703;CALLERS=freebayes,vardict,varscanClippingRankSum=0;DB;

I think this might actually be a VEP issue, as I have just observed the same running VEP outside of bcbio.

Many thanks for all the great work.

**Comment by tb08** [comment]
I found another issue that arises from the new decomposition before ensemble recall. The decompose step now turns the soft filters in the individual caller vcfs into hard filters (the variants are dropped). This is because ensemble.py calls the normalize function with the option passonly=True. which breaks the "use_filtered: true" functionality.
I think this is where the problem arises, in ensemble.py, line 40:
` vrn_files = [normalize.normalize(f, data, passonly=True, rerun_effects=False) for f in vrn_files] `
I find the use_filtered:true option very useful because it allows applying different filters from the default ones in bcbio.

**Comment by chapmanb** [comment]
Thank you for all this feedback and for reporting the issues. I've been digging into this and having trouble replicating the initial behavior you describe. I only have tests setup for snpEff so have been using that instead of VEP, but appear to get the final re-annotated, post decomposition, input in the final directory. Would you be able to share your configuration so I can see if I can replicate directly? Do you see the same problematic behavior if you use snpEff instead of VEP?

For the semicolon issue, it sounds like that gets caused during VEP annotation, is that right? If so, @matthdsm just integrated a new VEP version so it might be worth updating and seeing if we can replicate outside of bcbio so we can report upstream to the VEP maintainers.

Finally, I pushed a fix for the normalization/use_filtered issue where we'll now respect that flag.

Thanks again for all this help debugging and sorry for the inability to spot a fix for the first two problems. I'll work more on setting up to reproduce and hopefully we can shake out the underlying issues.

**Comment by tb08** [comment]
Hi Brad,
Thanks for the reply and the fix for use_filtered.
About the first issue, what config info would you need? I unfortunately cannot share data but you will find below the template yaml I use for my bcbio run. Thing is, I have been running different versions of bcbio in this analysis, maybe a clean re-run of all the variant calling is the way to go? (individual variant caller analyses were run with 1.06 while ensemble was rerun with 1.07).

Yes I think the semicolon issue happens after VEP annotation. I think it only happens when VEP is run on a file that already has a CSQ field and this CSQ field is not the last one in the INFO section because the missing semicolon location is always exactly where the CSQ field used to be before reannotating. Probably something about the way VEP removes the existing CSQ before appending the new one at the end of the INFO section. Having fields after CSQ seems to happen only starting with -decomposed.vcf.gz VCFs. I cannot ascertain it right now as I am upgrading bcbio and it's still working on getting VEP to v 91 and the downloads are taking a while, I will try running ensemble again and see if these glitches are still happening and whether it's only with vep and I'll report back here. Thanks again for all the help.

```
# Tumor only variant calling
---
details:
  - analysis: variant2
    genome_build: GRCh37
    algorithm:
     aligner: bwa
     mark_duplicates: true
     recalibrate: false
     realign: false
     remove_lcr: true
     platform: illumina
     quality_format: standard
     min_allele_fraction: 2
     variantcaller: [gatk-haplotype, freebayes, vardict, varscan]
     ensemble:
      numpass: 1
      use_filtered: true
     tools_off: [gemini,tumoronly-prioritization,upload_alignment]
     effects: vep
     effects_transcripts: canonical
     tools_on: [qualimap]
     variant_regions: ./regions_GRCh37.bed
upload:
    dir: ../final
```
