### ISSUE TITLE
configuration question

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#2243]
Hi Brad,

Lately, We've been trying to analyze some SNP panels using bcbio. This is fastq data from a MiSeq tabletop sequencer. However, we're seeing a tremendous slowdown while analyzing these samples.
Do you have any recommendations on settings to speed things up a bit?

We're using the following config:
```
#bcbio-nextgen v1.0.5
---
#include an experiment name here
fc_name:
upload:
  dir: ../final
globals:
  analysis_regions: RefSeqExomeAndPanels_20171003.bed
  coverage_regions: RefSeqExomeAndPanels_20171003.bed
resources:
  tmp:
    dir: /tmp/bcbio
details:
  - analysis: variant2
    genome_build: hg38
    algorithm:
      aligner: bwa
      save_diskspace: true
      coverage_interval: amplicon
      coverage: coverage_regions
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      variant_regions: analysis_regions
      jointcaller: gatk-haplotype-joint
      effects: false
      tools_off:
        - gemini
    # add the path to your files here
    files:
```

Note the regions file we're using. These are the same regions we use for our exome pipeline. Could this be the cause of the slowdown?

Thanks for the help
Cheers
M
