### ISSUE TITLE
Piped Bamprep with GATK3.8: ` '--analysis_type' is not in list `

### ISSUE THREAD

**Issue by tkoomar** [chapmanb/bcbio-nextgen#2264]
I have a fresh installation of bcbio, but am stuck needing to use GATK3 (with indel realignment, no less) for the remainder of a project. When my runs get to the piped bamprep step they either hang indefinitely with no new commands issued in the `bcbio-nexgen-commands.log`, or they produce the following in standard error: (full output in this [gist](https://gist.github.com/tkoomar/2b89145b1146fcb8561a7739e5c32be1))

```
...........................................................................
/Dedicated/jmichaelson-wdata/bcbio-dna/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py in cl_gatk(self=<bcbio.broad.BroadRunner instance>, params=['PrintReads', '-L', '12:1-133851895', '-R', '/Dedicated/jmichaelson-wdata/bcbio-dna/genomes/Hsapiens/GRCh37/seq/GRCh37.fa', '-I', '/Dedicated/jmichaelson-genome/SLI_WGS/reseq_pool...bio/work/align/sample288/sample288-sort-recal.bam'], tmp_dir='/nfsscratch/Users/tkoomar/tmpcbTXzq', memscale=None, parallel_gc=False)
    280                                  "installation.html#gatk-and-mutect-mutect2")
    281         is_gatk4 = "gatk4" not in dd.get_tools_off({"config": self._config})
    282         cores = self._config["algorithm"].get("num_cores", 1)
    283         config = self._config
    284         atype_index = params.index("-T") if params.count("-T") > 0 \
--> 285                         else params.index("--analysis_type")
        params.index = <built-in method index of list object>
    286         prog = params[atype_index + 1]
    287         # For GATK4 specify command first, so swap params to accomplish
    288         if is_gatk4:
    289             params = params[:]

ValueError: '--analysis_type' is not in list
```
I cannot shake the feeling that there is some change I should have made to my input  configuration, but I cannot figure out what it might be. The template I am using:
```
# Configuration 
---
upload:
  dir: ../final
details:
  - files: []
    description: sample
    metadata:
      batch: batch##
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      coverage_interval: genome
      mark_duplicates: true
      recalibrate: true
      realign: true
      save_diskspace: true
      tools_off:
      - gatk4 
      - gemini
      effects: vep
      variantcaller: gatk-haplotype
      remove_lcr: true
```
