### ISSUE TITLE
PrintReads - No parallelization

### ISSUE THREAD

**Issue by xexpanderx** [chapmanb/bcbio-nextgen#2265]
I have run bcbio on whole-genome and realized that the GATK PrintReads step is a major bottleneck. Right now I run only whole-genome on one individual. I can see that "nct" option is not defined looking at the log:

`[2018-02-12T23:45Z] compute02: export JAVA_HOME=/sw/compilers/oracle-jdk-1.8/1.8.0_152 && export PATH=/sw/compilers/oracle-jdk-1.8/1.8.0_152/bin:$PATH && /sw/pipelines/bcbio-nextgen/1.0.5/anaconda/bin/gatk -Xmx91728m -Djava.io.tmpdir=/gluster-storage-volume/projects/wp3/WGS/QE-1452/bcbio/bcbiotx/tmpmdp8Lc -T PrintReads -R /data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fasta -I /gluster-storage-volume/projects/wp3/WGS/QE-1452/bcbio/align/55683/55683-sort.bam -BQSR /gluster-storage-volume/projects/wp3/WGS/QE-1452/bcbio/align/55683/55683-sort-recal.grp -o /gluster-storage-volume/projects/wp3/WGS/QE-1452/bcbio/bcbiotx/tmpmdp8Lc/55683-sort-recal.bam -jdk_deflater -jdk_inflater -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment`

My bcbio-config looks like this:

```
---
# Configuration file specifying system details for running an analysis pipeline
# These pipeline apply generally across multiple projects. Adjust them in sample
# specific configuration files when needed.

# -- Base setup

# Define resources to be used for individual programs on multicore machines.
# These can be defined specifically for memory and processor availability.
# - memory: Specify usage for memory intensive programs. The indicated value specifies the wanted *per core* usage.
# - cores: Define cores that can be used for multicore programs.
# - jvm_opts: specify details
# - cmd: Command to launch the program, if not located on PATH.
# - dir: Directory containing program associated data. Especially useful for
#        java jars
resources:
  # default options, used if other items below are not present
  # avoids needing to configure/adjust for every program
  default:
    memory: 7G
    cores: 64
    jvm_opts: ["-Xmx7000m"]
  log:
    dir: /sw/pipelines/bcbio-nextgen/1.0.5/share/java/log
  tmp:
    dir: null
  ucsc_bigwig:
    memory: 7g
  bwa:
    cmd: bwa
    memory: 7g
    cores: 64
  samtools:
    memory: 7G
    cores: 64
  star:
    memory: 7g
    cores: 64
  snap:
    memory: 7G
    cores: 64
  kraken:
    memory: 7G
    cores: 64
  qsignature:
    memory: 7G
    cores: 64
  qualimap:
    memory: 7g
    cores: 64
  qsnp:
    jvm_opts: ["-Xmx7000m"]
  gatk:
    jvm_opts: ["-Xmx7000m"]
  gatk-haplotype:
    jvm_opts: ["-Xmx7000m"]
  gatk-vqsr:
    jvm_opts: ["-Xmx7000m"]
  picard:
    jvm_opts: ["-Xmx7000m"]
  snpeff:
    jvm_opts: ["-Xmx7000m"]
  bcbio_variation:
    jvm_opts: ["-Xmx7000m"]
#  rnaseqc:
#    dir: /sw/pipelines/bcbio/0.8.9/share/java/RNA-SeQC
#    jvm_opts: ["-Xmx7000m"]
#  mutect:
#    jvm_opts: ["-Xmx7000m"]
#    dir: /sw/pipelines/bcbio/0.8.9/share/java/mutect
  varscan:
    jvm_opts: ["-Xmx7000m"]
  vardict:
    jvm_opts: ["-Xmx7000m"]
  oncofuse:
    jvm_opts: ["-Xmx7000m"]
  express:
    memory: 7g
  dexseq:
    memory: 7g
  macs2:
    memory: 7g
  seqcluster:
    memory: 7g

# Location of galaxy configuration file, which has pointers to reference data
# https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#reference-genome-files
galaxy_config: universe_wsgi.ini

# -- Additional options for specific integration, not required for standalone usage.

# Galaxy integration. Required for retrieving information from Galaxy LIMS.
#galaxy_url: http://your/galaxy/url
#galaxy_api_key: your_galaxy_api_key

# Details for hooking automated processing to a sequencer machine.
# Not required if running standalone pipelines.
# analysis:
#   # Can specify a different remote host to initiate
#   # the copy from. This is useful for NFS shared filesystems
#   # where you want to manage the copy from the base machine.
#   copy_user:
#   copy_host:
#   store_dir: /store4/solexadata
#   base_dir: /array0/projects/Sequencing
#   worker_program: nextgen_analysis_server.py
```
Any way to parallelize PrintReads?

bcbio version used: 1.0.7a

**Comment by chapmanb** [comment]
Thanks for the detailed report and sorry about the issue. Are you in a position to update to the latest release (1.0.8)? This uses GATK4 by default and the BQSR step, which is bottlnecking your run here, is parallelized over multiple cores using the new GATK4 Spark implementations. If you have a recent 1.0.7a version you could also try adding `tools_on: [gatk4]` to your current configuration and it should make use of GATK4 over the current GATK 3 you have which is not parallelized. Hope this fixes things for you and please let us know if you run into other issues.

**Comment by xexpanderx** [comment]
Hi, do you mean like this (see the end):

```
---
# Configuration file specifying system details for running an analysis pipeline
# These pipeline apply generally across multiple projects. Adjust them in sample
# specific configuration files when needed.

# -- Base setup

# Define resources to be used for individual programs on multicore machines.
# These can be defined specifically for memory and processor availability.
# - memory: Specify usage for memory intensive programs. The indicated value specifies the wanted *per core* usage.
# - cores: Define cores that can be used for multicore programs.
# - jvm_opts: specify details
# - cmd: Command to launch the program, if not located on PATH.
# - dir: Directory containing program associated data. Especially useful for
#        java jars
resources:
  # default options, used if other items below are not present
  # avoids needing to configure/adjust for every program
  default:
    memory: 7G
    cores: 64
    jvm_opts: ["-Xmx7000m"]
  log:
    dir: /sw/pipelines/bcbio-nextgen/1.0.5/share/java/log
  tmp:
    dir: null
  ucsc_bigwig:
    memory: 7g
  bwa:
    cmd: bwa
    memory: 7g
    cores: 64
  samtools:
    memory: 7G
    cores: 64
  star:
    memory: 7g
    cores: 64
  snap:
    memory: 7G
    cores: 64
  kraken:
    memory: 7G
    cores: 64
  qsignature:
    memory: 7G
    cores: 64
  qualimap:
    memory: 7g
    cores: 64
  qsnp:
    jvm_opts: ["-Xmx7000m"]
  gatk:
    jvm_opts: ["-Xmx7000m"]
  gatk-haplotype:
    jvm_opts: ["-Xmx7000m"]
  gatk-vqsr:
    jvm_opts: ["-Xmx7000m"]
  picard:
    jvm_opts: ["-Xmx7000m"]
  snpeff:
    jvm_opts: ["-Xmx7000m"]
  bcbio_variation:
    jvm_opts: ["-Xmx7000m"]
#  rnaseqc:
#    dir: /sw/pipelines/bcbio/0.8.9/share/java/RNA-SeQC
#    jvm_opts: ["-Xmx7000m"]
#  mutect:
#    jvm_opts: ["-Xmx7000m"]
#    dir: /sw/pipelines/bcbio/0.8.9/share/java/mutect
  varscan:
    jvm_opts: ["-Xmx7000m"]
  vardict:
    jvm_opts: ["-Xmx7000m"]
  oncofuse:
    jvm_opts: ["-Xmx7000m"]
  express:
    memory: 7g
  dexseq:
    memory: 7g
  macs2:
    memory: 7g
  seqcluster:
    memory: 7g

# Location of galaxy configuration file, which has pointers to reference data
# https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#reference-genome-files
galaxy_config: universe_wsgi.ini

# -- Additional options for specific integration, not required for standalone usage.

# Galaxy integration. Required for retrieving information from Galaxy LIMS.
#galaxy_url: http://your/galaxy/url
#galaxy_api_key: your_galaxy_api_key

# Details for hooking automated processing to a sequencer machine.
# Not required if running standalone pipelines.
# analysis:
#   # Can specify a different remote host to initiate
#   # the copy from. This is useful for NFS shared filesystems
#   # where you want to manage the copy from the base machine.
#   copy_user:
#   copy_host:
#   store_dir: /store4/solexadata
#   base_dir: /array0/projects/Sequencing
#   worker_program: nextgen_analysis_server.py
tools_on: [gatk4]
```
