### ISSUE TITLE
TitanCNA: did not find compatible variant calling files

### ISSUE THREAD

**Issue by lemdcock** [chapmanb/bcbio-nextgen#2288]
Dear B. Chapman,

As I have already run mutect2, I was wondering if I could supply the final vcf file to the structural variant calling pipeline using cnvkit and titanCNA. Or is it better to run the variant calling and structural variant calling in tandem? 

Kind regards,
Laurenz

My current sample yaml file:
```
#!yaml
---
details:
  - analysis: variant2
    description: sample-1
    files:
      - sample-1.bam
    genome_build: hg38
    algorithm:
      platform: illumina
      coverage_interval: regional
      mark_duplicates: false
      recalibrate: false
      realign: false
      variantcaller: false
      indelcaller: false
      svcaller: [cnvkit, titancna]
      variant_regions: /home/lemdcock/RefSeqExomeAndPanels_20171003.bed
      sv_regions: /home/lemdcock/RefSeqExomeAndPanels_20171003.bed
      effects: false
      tools_off: gatk4
    metadata:
      batch: CNV_LOH
      phenotype: tumor
  - analysis: variant2
    description: sample-2
    files:
      - sample-2.bam
    genome_build: hg38
    algorithm:
      platform: illumina
      coverage_interval: regional
      mark_duplicates: false
      recalibrate: false
      realign: false
      variantcaller: false
      indelcaller: false
      svcaller: [cnvkit, titancna]
      variant_regions: /home/lemdcock/RefSeqExomeAndPanels_20171003.bed
      sv_regions: /home/lemdcock/RefSeqExomeAndPanels_20171003.bed
      effects: false
      tools_off: gatk4
    metadata:
      batch: CNV_LOH
      phenotype: normal
upload:
  dir: /home/lemdcock/output/
```
