### ISSUE TITLE
adding new samples to incremental calling pipeline

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#727]
I'd like to run the joint calling pipeline on about 1000 exomes. The data will be arriving in dribs and drabs with eventual numbers substantially larger. Is there a recommended process (yaml code snippet) for adding new samples to a project that uses the joint calling pipeline? 

I'll start with Freebayes but I got the impression gvcf support was somewhat outside the EG's philosophy. 
https://github.com/ekg/freebayes/issues/76

p.s. Do you want usage questions posted to Biostars?

**Comment by chapmanb** [comment]
Daryl;
Thanks for the questions. Happy to take them wherever works. If you use the bcbio tag on Biostars I should get a notification and heads up.

We don't have an automtic way to do this incremental analysis right now, but you can do it by calling all of the samples in batches as they come in and then running a second analysis feeding all of the samples into just joint calling with a per-sample configuration like:
```
- algorithm:
    aligner: false
    jointcaller: freebayes-joint
    mark_duplicates: false
    realign: false
    recalibrate: false
    variantcaller: false
  analysis: variant2
  description: name
  files: aligned.bam
  genome_build: GRCh37
  metadata:
    batch: all_of_em
  vrn_file: individual_call.vcf.gz
```
For FreeBayes you do have to keep all of the BAMs around because of the gVCF deficiencies Erik is worried about. I did this approach successfully for 1500 whole genome samples so it will work at your scale, but it is computationally more expensive than the GATK gVCF approach.

Hope this helps.
