### ISSUE TITLE
File streaming problems from s3?

### ISSUE THREAD

**Issue by rronen** [chapmanb/bcbio-nextgen#744]
Hi Brad/Rory/John,

I've been trying out bcbio_vm on AWS (tumor/normal calling on a couple BAMs from s3 bucket). I was able to set up and start a cluster, and ssh into the head-node to start the run. However, I am getting different errors in the alignment step. First it was a paired read missing ("samblaster: Can't find first and/or second of pair in sam block of length 1 for id: X:XXX:XX:X:XX samblaster: Are you sure the input is sorted by read ids?"); after deleting the 'work' dir and restarting the run I got a different error ("pysam: SEQ and QUAL are of different lengths"). 

Running the same input BAMs & config on a local bcbio-nextgen full install (not bcbio_vm) I don't get any of these errors. I suspect something may be going wrong related to streaming the input files from s3 (perhaps related to gof3r?), although this is a total guess.

Just wanted to report this and see if you've run into anything similar, and if so what you'd recommend.

(Unrelated question: is there a simple way to directly re-run certain commands with the docker setup? This would be pretty straightforward on a full/local install since all the tools & data are accessible, wondering if there's an equivalent "debug procedure" with docker -- apologies in advance if this is already answered somewhere in the docs)

**Comment by roryk** [comment]
Hi Roy,

Thanks for posting about the issue. We’ve been working out the kinks running with bcbio_vm and it looks like you ran into one. Just to start, by any chance, are you running out of space on your cluster on AWS? It sounds like the files might be getting truncated.

Best,

Rory

**Comment by rronen** [comment]
Hi Rory,

Thanks for the quick reply! Nope, space doesn't seem to be a problem (120G still available). 

Just to add some info, I am running on a "single-node cluster" configuration so the head-node is doing all the processing (instance type is c3.2xlarge with 200G "general purpose SSD" boot drive).

Thanks!
Roy

**Comment by rronen** [comment]
FYI, another restart of the analysis ended with a new error:

'''
[M::mem_pestat] (25, 50, 75) percentile: (264, 342, 455)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 837)
[M::mem_pestat] mean and std.dev: (368.65, 140.54)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1028)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
sambamba-sort: Unable to write to stream
samtools: writing to standard output failed: Broken pipe
samtools: error closing standard output: -1
samblaster: Unable to write to output file.

[fputs] Broken pipe
sambamba-sort: unable to write to stream
sambamba-sort: unable to write to stream
' returned non-zero exit status 1
ubuntu@ip-10-144-102-110:~/p3_analysis/p3_1_B1_tumor_normal_fb_vs/work_test$ 
ubuntu@ip-10-144-102-110:~/p3_analysis/p3_1_B1_tumor_normal_fb_vs/work_test$ 
ubuntu@ip-10-144-102-110:~/p3_analysis/p3_1_B1_tumor_normal_fb_vs/work_test$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1      197G  132G   58G  70% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
udev             15G  8.0K   15G   1% /dev
tmpfs           3.0G  248K  3.0G   1% /run
none            5.0M     0  5.0M   0% /run/lock
none             15G     0   15G   0% /run/shm
none            100M     0  100M   0% /run/user
/dev/xvdb        74G  180M   70G   1% /mnt
'''

**Comment by lpantano** [comment]
Hi,

I would check `/var/log/message` or any other system log.

maybe there are some error there that can help.

**Comment by chapmanb** [comment]
Roy;
Sorry about the issues. I'll try to work to reproduce to see if we can isolate an underlying cause. Would you be able to share your input configuration (no need to have the exact files, just the configuration) so I can try to replicate?

For alignment, we first pull the entire fastq file locally to avoid any gof3r streaming issues. I had hopes that we could stream the entire thing from S3 but found intermittent failures when doing that so shelved the idea. I can try to identify if there's something else going on.

Debugging exact runs with docker tools is trickier, as you can't immediately re-run commands. This is something where we'll have to work on additional tooling but don't have it right now.

Thanks much for trying this all out.

**Comment by rronen** [comment]
Hi Brad,

Thanks, I appreciate the help in tracking this down. The configuration is:

Perhaps because the inputs are BAM it still tries to stream using gof3r?

```
details:
- algorithm:
    aligner: bwa
    coverage_interval: exome
    indelcaller: false
    mark_duplicates: true
    phasing: false
    platform: illumina
    quality_format: Standard
    realign: true
    recalibrate: true
    variantcaller:
    - varscan
    - freebayes
  analysis: variant2
  description: p3_T_1B1
  files:
  - s3://my-bucket/my-folder/tumor.bam
  genome_build: GRCh37
  metadata:
    batch: batch1
    phenotype: tumor
    sex: female
- algorithm:
    aligner: bwa
    coverage_interval: exome
    indelcaller: false
    mark_duplicates: true
    phasing: false
    platform: illumina
    quality_format: Standard
    realign: true
    recalibrate: true
    variantcaller:
    - varscan
    - freebayes
  analysis: variant2
  description: p3_N
  files:
  - s3://my-bucket/my-folder/normal.bam
  genome_build: GRCh37
  metadata:
    batch: batch1
    phenotype: normal
    sex: female
fc_date: '2015-01-31'
fc_name: p3_1_B1_tumor_normal
upload:
  bucket: my-bucket
  dir: /home/ubuntu/run/bcbio-vm-test1/final  
  folder: my-folder/final
  method: s3
```
