### ISSUE TITLE
AssertionError: Analysis RNA-Seq is not supported by bowtie2

### ISSUE THREAD

**Issue by rronen** [chapmanb/bcbio-nextgen#795]
Hi @chapmanb, @roryk,

Following the example [here](https://bcbio-nextgen.readthedocs.org/en/latest/contents/pipelines.html#configuration) for RNA-Seq config, I set the aligner to tophat2 but am getting this error (that mentions bowtie2):

```
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bowtie2.py", line 35, in align
    assert analysis_config, "Analysis %s is not supported by bowtie2" % (data["analysis"])
AssertionError: Analysis RNA-Seq is not supported by bowtie2
``` 

Configuration contents:
```
details:
- algorithm:
    adapters: [polya, truseq]
    align_split_size: 5000000
    aligner: tophat2
    nomap_split_targets: 100
    platform: illumina
    quality_format: standard
    strandedness: unstranded
    trim_reads: read_through
  analysis: RNA-Seq
  description: p2-1B1
  files: [TEST1.fastq, TEST2.fastq.gz]
  genome_build: GRCh37
  metadata: {batch: batch1}
upload: {dir: ../final}
```

It works when setting the aligner to `bwa`, but is this recommended best practice? I'm far from expert on RNA-Seq so I might be missing something basic here...
