### ISSUE TITLE
local scratch

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#836]
I just noticed a folder literally named `$LOCAL_SCRATCH` in my work directory. I'm using the joint calling pipeline from todays dev code. The pipeline is failing but not sure if this is related. Would this be expected if something went wrong like it couldn't find the directory or was full?

```
# yaml
resources:
  tmp:
    dir: $LOCAL_SCRATCH

# path
echo $LOCAL_SCRATCH
/local-scratch/dwaggott/2107640
```
