### ISSUE TITLE
Automated sample configuration only works with .fastq.gz files

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#860]
I tried making a sample configuration (with template and so on) using ready-made BAM files to prevent yet another alignment run, but when running bcbio_nextgen I was greeted with "metadata not found" for each of the samples.

Example YAML produced by the run:

````yaml
  description: 10152
  metadata:
    batch: OTH14
  files:
  - /mnt/data/projects/OTH-14/bam/10152.bam
````

The file names and the metadata are identical, but they don't get picked up, somehow.
