### ISSUE TITLE
Define temporary directory in yaml file

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#893]
I have some shared filesystem IO by writing temporary files to the local disk on cluster systems with large attached local storage. I am trying to use the following section in the yaml file to use the local /tmp directory.
```
resources:
  tmp:
    dir: /tmp

Where should I put the section into the yaml file? 

The following is the yaml file orginal template for my running.

details:
- algorithm:
    align_split_size: 5000000
    aligner: bwa
    ensemble:
      numpass: 2
    indelcaller: false
    mark_duplicates: true
    nomap_split_targets: 100
    platform: illumina
    quality_format: standard
    realign: true
    recalibrate: true
    remove_lcr: true
    variantcaller:
    - mutect
    - freebayes
    - vardict
    - varscan
  analysis: variant2
  description: 101-FFPE-tumor
  files:
  - /.../101-FFPE-tumor_R1.fastq.gz
  - /.../101-FFPE-tumor_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: batch101
    phenotype: tumor
- algorithm:
    align_split_size: 5000000
    aligner: bwa
    ensemble:
      numpass: 2
    indelcaller: false
    mark_duplicates: true
    nomap_split_targets: 100
    platform: illumina
    quality_format: standard
    realign: true
    recalibrate: true
    remove_lcr: true
    variantcaller:
    - mutect
    - freebayes
    - vardict
    - varscan
  analysis: variant2
  description: 101-normal
  files:
  - /.../101-normal_R1.fastq.gz
  - /.../101-normal_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: batch101
    phenotype: normal
fc_date: '2015-06-17'
fc_name: BC
upload:
  dir: ../final
```

Thanks for answering!
